### ISSUE TITLE
Demos tests skipped

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/rxode2#113]
The demos test never runs for me.  It's not clear how to make it run:

https://github.com/billdenney/nlmixr2CRANtesting/blob/db29c0bd2424e6de968a179c2fbdc2502c9ea82e/outputs/rxode2_test.txt#L261-L264

**Comment by mattfidler** [comment]
You have to install the package with the demos.  I think the default changed at some point.  If I install and run `rxTest()` it will run the demos (I think)
