### ISSUE TITLE
y argument is ignored in `plot.rxSolveConfint1()` and `plot.rxSolveConfint2()`

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/rxode2#128]
I think that the `y` argument should allow for compartment selection in `plot.rxSolveConfint1()` and `plot.rxSolveConfint1()` the same as `plot.rxSolve()`.

Overall, the `plot.rxSolveConfint1()` and `plot.rxSolveConfint2()` functions are a bit confusing to me because they appear to have some detailed requirements internally.  I'm just looking at them for the first time, though.

**Comment by mattfidler** [comment]
may take some thought

**Comment by billdenney** [comment]
My first thought is:  I think that there should be an explicit test that `y` is missing to prevent someone from accidentally having a passed argument swallowed.

I'd need to test it a bit more to see about if I think a `y` argument could be helpful.
