### ISSUE TITLE
Simplification Question:  Can `rxStack` be retired in favor of `tidyr::pivot_longer`?

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/rxode2#131]
Can `rxStack` be retired in favor of `tidyr::pivot_longer`?

The downside I see of doing this is that it adds tidyr as a dependency (which may be reason enough not to do it).  The upside I see is that issues like #118 would not occur.

**Comment by mattfidler** [comment]
I don't wish to do this. It queries model properties as well.

**Comment by mattfidler** [comment]
My philosophy is why introduce a dependency (especially one that changes as much as tidy verse) if we already have a solution that works. But perhaps I am thinking narrowly here.  Feel free to point out something I am missing.

I still am uncomfortable with the large dependencies and lead more toward tiny dependency footprints.  As discussed earlier `rxode2` already has way too many dependencies.

**Comment by billdenney** [comment]
I'm mostly neutral here.

My general philosophy is to shrink the code base if there is another solution that is heavily tested which does the same thing, when possible.  That said, the tidyverse changes a lot, and I'd only choose to take their dependencies when required.  (Balancing that:  The tidyverse also has a lot of very useful functions within.  This time I'm neutral because it's a smaller function.

Since I can work with R code and not C++ code, I also have a bias to move more non-time-critical code to R (e.g. not part of an inner loop of estimation).  That's completely a bias though.

**Comment by mattfidler** [comment]
I think that is reasonable point of view.  For now I am not interested.  Maybe I will change my mind in the future.

For me this is not as important as moving other parts to R.  I think that there are other things that could be ported to R (for example the event table creation would probably be better in R, though supporting everything that was supported with small effective functions could also be a challenge).

**Comment by mattfidler** [comment]
I would be more inclined to use the `data.table` equivalent since it is threaded and is required indirectly by the c-level `rxode2`.  That being said, I am not as familiar with `data.table` and it changes often too (perhaps not as often as tidyverse).

**Comment by mattfidler** [comment]
Because of the internal requirement, I have been trying to use `data.table` whenever possible.
