### ISSUE TITLE
Feature request: `rxLhs()` and `rxState()` work on more objects

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/rxode2#140]
I think that it'd be handy if `rxLhs()` worked on more types of objects.  Specifically, it would be handy if it worked on `rxUi` objects and maybe even `function`s.

``` r
library(rxode2)
#> rxode2 1.0.0 using 4 threads (see ?getRxThreads)
#>   no cache: create with `rxCreateCache()`
pheno2 <- function() {
  ini({
    tcl <- log(0.008) # typical value of clearance
    tv <-  log(0.6)   # typical value of volume
    ## var(eta.cl)
    eta.cl + eta.v ~ c(1, 
                       0.01, 1) ## cov(eta.cl, eta.v), var(eta.v)
    # interindividual variability on clearance and volume
    add.err <- 0.1    # residual variability
  })
  model({
    cl <- exp(tcl + eta.cl) # individual value of clearance
    v <- exp(tv + eta.v)    # individual value of volume
    ke <- cl / v            # elimination rate constant
    d/dt(A1) = - ke * A1    # model differential equation
    cp = A1 / v             # concentration in plasma
    cp ~ add(add.err)  # define error model
  })
}

simdata <- data.frame(time=1:10, ID=factor(c("A", "B")))

sim <- rxSolve(pheno2, events=simdata)
#> i parameter labels from comments will be replaced by 'label()'

rxLhs(pheno2)
#> Error in rxLhs(pheno2): Not compatible with STRSXP: [type=NULL].
rxLhs(rxode2(pheno2))
#> i parameter labels from comments will be replaced by 'label()'
#> class:   rxUi    
#> Error in rxLhs(rxode2(pheno2)): need an rxode2-type object to extract model variables
rxLhs(sim)
#> [1] "cl"       "v"        "ke"       "cp"       "ipredSim" "sim"
```

<sup>Created on 2022-03-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by billdenney** [comment]
And the same for `rxState()`

**Comment by billdenney** [comment]
Maybe, `rxUiGet()`, too.  But, I'm not exactly sure what it is intended to do.

**Comment by mattfidler** [comment]
`rxUiGet` is an internal S3 method that allows you to extend the UI function.  If you create a `S3` method `rxUiGet.bill` you can then access `fun$bill`   The input argument is a `list`.  The first item is the `rxode2` ui environment and the second is the `exact matches` argument.  If you have an attribute on the method `attr(rxUiGet.bill, "desc")`  it will show the description of the `str` method and will complete with `tab` completion

**Comment by mattfidler** [comment]
So, no it really shouldn't work on more objects.

**Comment by mattfidler** [comment]
Should work.  I am not sure if you are notified about closing from a pull request.

**Comment by billdenney** [comment]
Thanks, I'll test it out later today.  I do get closing notifications.

**Comment by billdenney** [comment]
This is great, thanks!
