### ISSUE TITLE
Feature request: Add an `append` argument to `ini()`

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/rxode2#143]
I think it would be helpful to add an `append` argument to `ini()` so that initial conditions could be added the same way as `model()`.  Or, is there a different way to add another parameter?

**Comment by mattfidler** [comment]
Parameters are added and deleted with the model block.  They are assigned the types of parameters with these rules (from the model piping vignette):

Note that new between subject variability parameters are distinguished from other types of parameters (ie population parameters, and individual covariates) by their name. Parameters starting or ending with the following names are assumed to be between subject variability parameters:

eta (from NONMEM convention)
ppv (per patient variability)
psv (per subject variability)
iiv (inter-individual variability)
bsv (between subject variability)
bpv (between patient variability)

Everything else is a population level parameter.  

I am unsure a use case for appending parameters to an `ini` block

**Comment by billdenney** [comment]
Thanks for pointing me to the modelPiping vignette.  Yes, that is definitely where this should live, and I will merge them.  I have a question about adding between-subject variability, and I'll ask that in a new issue since it's only tangentially-related here.

**Comment by mattfidler** [comment]
Based on #144 I think regardless of the approach appending parameters does not make sense here.
