### ISSUE TITLE
Feature request: Modify how BSV is added to parameters via `model()` and `ini()`

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/rxode2#144]
Original comment spurring the thought:

> Parameters are added and deleted with the model block.  They are assigned the types of parameters with these rules (from the model piping vignette):
> 
> Note that new between subject variability parameters are distinguished from other types of parameters (ie population parameters, and individual covariates) by their name. Parameters starting or ending with the following names are assumed to be between subject variability parameters:
> 
> eta (from NONMEM convention)
> ppv (per patient variability)
> psv (per subject variability)
> iiv (inter-individual variability)
> bsv (between subject variability)
> bpv (between patient variability)
> 
> Everything else is a population level parameter.  
> 
> I am unsure a use case for appending parameters to an `ini` block
> 

_Originally posted by @mattfidler in https://github.com/nlmixr2/rxode2/issues/143#issuecomment-1071992473_

**Comment by billdenney** [comment]
Automatic selection based on names seems like it will get the result correct most of the time, but occasionally, it will miss something.

I am writing the below to try to work out what I think may be more intuitive and/or less error prone.  I'm not at all wed to the specific idea, but I do think that it could be useful to make the process of parameter addition to the model more in sync with the way that it is done when creating a model.

I had not recently read the modelPiping vignette, and so, before reading the comment above, I did not have an immediate idea of how to add a BSV parameter.  As a user, I would have assumed that I could add the BSV parameter with `ini(mybsv~0.1)` where the formula notation would have caused it to be BSV instead of a fixed effect.  (I intentionally made the name something that wouldn't be caught by the naming rules.)

So, my thought process is:

* Adding a variable should be clear to the user exactly what they are adding, and it should do what they intend (even if they haven't read all of the docs).
* The user should be able to override the default behavior (e.g. if they want to make a theta named `bsvariable # my boss made me add this BS variable`, then that should be allowed and controllable).
    * I also think that this could hit accidentally with some forms of model automation.  For example, if working with stepwise covariate modeling, I could see an accidental BSV addition there.
* When something automatically happens in the background, a message should tell the user what is happening.  (I'm thinking of the fact that a parameter is automatically added as BSV which may be a surprise to the user.)

My initial thoughts on how to do this are:

* I'm pretty sure that there is a requirement that the model is always in a consistent state (which is a good thing).  So, the parameter has to be added to the `model()` before it can be modified in the `ini()`.  I think that this is the way it works now.
* I lean toward less in terms of assumptions of what the user intends with a parameter in the model.
    * I think that the current method is:
        * If it starts (or ends?) with `cov`, make it a fixed effect.
            * How is the initial value assigned and how is the user notified?
        * If it starts or ends with `bsv`, `iiv`, etc. (the prefixes listed in https://github.com/nlmixr2/nlmixr2est/blob/182981cb70977951170af09584597588af3a49d2/vignettes/modelPiping.Rmd#L184-L189), make it a new random effect.
            * How is the initial value assigned and how is the user notified?
    * My preference would be a future state where:
        * No automation occurs behind the scenes for assignment of a new parameter as a fixed or random effect.  (Perhaps with an option to turn on automation.)
            * So, when adding a new part to the model like `my_model %>% model({ka=exp(tvka+iivka)`, `iivka` is assumed to come from the dataset instead of being added as a new parameter-- not a fixed nor random effect.
        * The parameter must be added to the model before it can be added/modified by `ini()`.
        * Any value in the list of covariates from the model can be added as a new parameter (because it is a value that is not attached to an existing parameter or a covariate).  If it's not in the covariate list, that is an error.
        * Detection of BSV occurs as follows:
            * If the assignment uses formula notation (`ini(bsv.cl~0.1)`), then it is a random effect to mirror what is already done in `ini()` when manually writing a model.
                * This feels like what a typical user may do.  (More to the point, I did it when trying earlier.)
            * If the assignment does not use formula notation, there is a way to specify that the parameter is a random effect such as using either a vector of parameters or possibly using a regular expression matching the parameter names (e.g. `ini(bsv.cl=1, .iiv.pattern="bsv.cl")`
                * This could be made backward compatible by setting a default of `.iiv.pattern="^(eta|ppv|psv|iiv|bsv|bpv).*$"`.  The pattern is not tested, and it doesn't match those strings at the end, but the idea holds that backward compatibility is achievable here.
        * Anything not detected as BSV is assigned as a fixed effect.
        * Removing all references to a parameter from the `model()` block will remove it from the parameters automatically, with a message that the parameter was removed.
             * I don't think that it makes sense to have the ability to directly remove a parameter via `ini()`.  But, maybe there is a use case that I can't immediately think of.
        * You cannot directly change something from being a fixed to a random effect.  You must remove it from the model and re-add it as the type of parameter you want it to be.

Manifesto complete.  😄

**Comment by mattfidler** [comment]
I think this probably takes a broader discussion/alignment.  But regardless of the approach appending to `ini` doesn't seem to make sense I believe

**Comment by billdenney** [comment]
From the discussion, this will be fixed when the following sub-issues are closed.  That said, I will close this issue in favor of those other, more focused issues:  #145, #146, and #147.
