### ISSUE TITLE
Remove rxode2Test()

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/rxode2#19]
As discussed in #17, we plan to remove `rxode2Test()`.  The `test` argument to `rxode2Test()` has the following values where the only values suggested in the documentation are "CRAN and not cran".

The `rxode2Test()` code suggest that it:
* runs all tests if `test="cran"`
* Runs other tests, only if `Sys.getenv("NOT_CRAN") == "true"` (I think that is set by testthat)
* And otherwise skips the tests

I think that the underlying goal is to run all tests where `test="cran"` and skip tests that aren't labeled `test="cran"` on CRAN (but run them locally and on CI).  Is that correct?

Second to that, there are several values other than "cran" for `test`.  Do they need to be preserved?  The other values used are:

* demo
* focei
* indLin
* lincmt
* lvl2
* norm
* parseLincmt
* parsing
* plot
* print
* rxuse

**Comment by mattfidler** [comment]
For now we can remove all the extra tags.  If we need to split out tests for timing reasons we can do so later.

I think the testthat interface is fine, but it may be easier to compare the environmental variable value directly.  I will leave the decision to you.

**Comment by billdenney** [comment]
Before starting this, I noticed an issue.  As I switched from Linux (where it's a bit easier to test because the system is faster) to Windows (where it's a bit easier to code since that's my desktop), there were test failures and warnings that were not there on Linux.  My guess is that something about the difference between Linux and Windows will also point us to the difference between Linux and CI.

So, my goal with the PR that I will generate is to try to maintain the same number of tests passing, but there may be more local failures.  Hopefully, that will take us to a state where we can find all the underlying differences and iron them out.

**Comment by billdenney** [comment]
While working on this, I see a few other simplifications where I think other functions would be a better fit.  Specifically, what I have identified are below (this list will be updated if/as I find more examples):

* `set.seed()` is better to use `withr::with_seed()` as it will make the seed change self-contained.
* the `.rxWithOptions()` function could be retired in favor of `withr::with_options()`

**Comment by billdenney** [comment]
While working on `test-000-modelVars.R`, I have two questions:

Q1: The line below has a difference in the `timeId` list element.  That looks like it is a compilation time or similar and the issue is that compilation took a couple of seconds on my system.  That seems like it could cause intermittent failures, so I'm ignoring the `timeId` element.  Is that okay?

https://github.com/nlmixr2/rxode2/blob/db7abf9a5c1822205036e43c3658462cfbdc64b5/tests/testthat/test-000-modelVars.R#L41

Q2: A file is being saved during the testing.  I think that should go away.  Is that correct?
https://github.com/nlmixr2/rxode2/blob/db7abf9a5c1822205036e43c3658462cfbdc64b5/tests/testthat/test-000-modelVars.R#L42

**Comment by mattfidler** [comment]
> While working on this, I see a few other simplifications where I think other functions would be a better fit. Specifically, what I have identified are below (this list will be updated if/as I find more examples):
> 
> * `set.seed()` is better to use `withr::with_seed()` as it will make the seed change self-contained.
> * the `.rxWithOptions()` function could be retired in favor of `withr::with_options()`

In general yes, though `withr::with_seed()` will likely need to be replaced eventually (ie #20).  I think I tried to remove any `withr::` dependencies to reduce my dependency count for CRAN.  For testing it is fine since It can use a simple `Suggests`, for internal functions it is a largder ask because it introduces a dependency.

**Comment by mattfidler** [comment]
> Q1: The line below has a difference in the timeId list element. That looks like it is a compilation time or similar and the issue is that compilation took a couple of seconds on my system. That seems like it could cause intermittent failures, so I'm ignoring the timeId element. Is that okay?

Yes, though it would be helpful to simply exclude it from the test....

**Comment by mattfidler** [comment]
> Q2: A file is being saved during the testing. I think that should go away. Is that correct?

Well it writes the documentation of the types of functions for `linCmt()' here: https://nlmixrdevelopment.github.io/RxODE/articles/RxODE-model-types.html#solved-compartment-models

What do you think?

**Comment by mattfidler** [comment]
> Q3: It looks like most of the tests are repeated. So, can those apparently duplicated tests be removed? Specifically, this line

Seems fine to me.

**Comment by billdenney** [comment]
Q1: It will be excluded.
Q2: If it helps for writing the documentation, then it makes sense to keep.  (Though, I think it should go somewhere more closely related to the documentation itself.)
Q3: Tests removed.

**Comment by mattfidler** [comment]
> Q2: If it helps for writing the documentation, then it makes sense to keep. (Though, I think it should go somewhere more closely related to the documentation itself.)

Looking at it again, remove it.  I was thinking of another test.

**Comment by billdenney** [comment]
Q2: Removed.

Q4: Any reason that this line should not use `to=10, by=0.5` instead of `to=100, by=0.01`?  I ask because the tests run slowly due to the number of simulated rows.  I've checked, and the tests pass the same either way, but if there is a reason to need the granularity, we should keep it.

https://github.com/nlmixr2/rxode2/blob/db7abf9a5c1822205036e43c3658462cfbdc64b5/tests/testthat/test-cov.R#L17

**Comment by billdenney** [comment]
Q5: The file `tests/testthat/test-data-setup.qs` appears to be unused.  Can it be deleted?

**Comment by mattfidler** [comment]
> Q4: Any reason that this line should not use to=10, by=0.5 instead of to=100, by=0.01? I ask because the tests run slowly due to the number of simulated rows. I've checked, and the tests pass the same either way, but if there is a reason to need the granularity, we should keep it.

The covariate test makes sure that covariate interpolation is working correctly.  I think it would be fine to remove it.  I think It may have upped it when debugging covariate interpolation.  I think linear covariate search may not be working well
