### ISSUE TITLE
Feature Request: Option to change how rate/dur/bioavailibility are inter-related

### ISSUE THREAD

**Issue by mattfidler** [nlmixr2/rxode2#204]
In `monolix` with `tinf` it seems that only rate is adjusted with bioavailability changes instead of duration.

**Comment by billdenney** [comment]
Changing duration seems unusual to me for the definition of bioavailability.

I think of bioavailability affecting the amount that makes it from compartment X to Y (usually depot to central).  Amount is *usually* correlated with rate and not duration.  Do you have an example where it affects duration?  (The one time I've seen bioavailability affect duration was when an IV infusion had adsorption to the tubing.)

**Comment by mattfidler** [comment]
`rxode2` matches `NONMEM` (and `monolix`, and even `mrgsolve`'s behavior).  When changing bioavailability with a rate, the rate remains constant, not the duration (ie the duration lengthens or shortens).

I agree with your assessment, and introduced a `dur` data item where the duration stays the same but the `rate` changes with bioavailbility.  

My mneumonic is that whatever is in the dataset is fixed, whatever is not in the dataset can vary.

This request is again to deal with `monolix`.  Monolix has a similar data item to nlmixr's `dur`:  `tinf`.  Unfortunately according to their documentation only rates change with changes in bioavilability (they use `p` for bioavailnibility).  

So... even though I think what I have done is the "right" thing, to reproduce monolix models, this request was made

**Comment by mattfidler** [comment]
This was taken care of with babelmixr2 so no for now
