### ISSUE TITLE
Feature consideration: Deprecate the `events` argument in rxSolve() to rename it `data`

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/rxode2#206]
Suggestion: Deprecate the `events` argument in rxSolve() to rename it `data`.

The rationale is that `data` would then be consistent between `nlmixr()` and `rxSolve()` making it easier for users to translate between the two.  The amount of deprecation could be very low (i.e. it could stay as a warning for a very long time-- no need to actually remove the `events` argument until `rxode3`, for instance).

**Comment by mattfidler** [comment]
Too late.  Already under cran review

**Comment by billdenney** [comment]
2.0.7?

**Comment by mattfidler** [comment]
I can see the value of what you are saying.  At the same time, I know you can simply run

```r
nlmixr(model, data, "rxSolve", rxControl()) 
```

It is not only consistent but it is the same function.

The effort involved in refactoring `events` to `data` would require changing `C` code `C++` code and R code, so based on the argument above I am not in favor of doing this.

**Comment by billdenney** [comment]
That's fair.
