### ISSUE TITLE
error building model

### ISSUE THREAD

**Issue by 1osde** [nlmixr2/rxode2#214]
I have installed the rxode2 package in R. But one error occured when building the model. 
The error is as follows:

C:/PROGRA~1/R/R-42~1.0/etc/x64/Makeconf:274: warning: overriding commands for target `.m.o'
C:/PROGRA~1/R/R-42~1.0/etc/x64/Makeconf:267: warning: ignoring old commands for target `.m.o'
process_begin: CreateProcess(NULL, basename rx_073eb8c6cf7abc1492df4aa0ca30126b_x64.dll .dll, ...) failed.
process_begin: CreateProcess(NULL, basename rx_073eb8c6cf7abc1492df4aa0ca30126b_x64.dll .dll, ...) failed.
process_begin: CreateProcess(NULL, basename rx_073eb8c6cf7abc1492df4aa0ca30126b_x64.dll .dll, ...) failed.
"zrx_073eb8c6cf7abc1492df4aa0ca30126b_x64.o" was unexpected at this time.
make: *** [rx_073eb8c6cf7abc1492df4aa0ca30126b_x64.dll] Error 255

**Comment by mattfidler** [comment]
Could tou post a reproducible example so I can help you?

**Comment by 1osde** [comment]
Dear Matthew Fidler, 


 I have copied the code and reproducible example as the following. The error occured when building the model with rxode2() function. 




> library(rxode2)
rxode2 2.0.7 using 8 threads (see ?getRxThreads)
  no cache: create with `rxCreateCache()`
> library(ggplot2)
> mod1 <- rxode2({
+   C2 <- centr/V2;
+   C3 <- peri/V3;
+   d/dt(depot) <- -KA*depot;
+   d/dt(centr) <- KA*depot - CL*C2 - Q*C2 + Q*C3;
+   d/dt(peri)  <- Q*C2 - Q*C3;
+   d/dt(eff)   <- Kin - Kout*(1-C2/(EC50+C2))*eff;
+ })


C:/PROGRA~1/R/R-42~1.0/etc/x64/Makeconf:274: warning: overriding commands for target `.m.o'
C:/PROGRA~1/R/R-42~1.0/etc/x64/Makeconf:267: warning: ignoring old commands for target `.m.o'
process_begin: CreateProcess(NULL, basename rx_073eb8c6cf7abc1492df4aa0ca30126b_x64.dll .dll, ...) failed.
process_begin: CreateProcess(NULL, basename rx_073eb8c6cf7abc1492df4aa0ca30126b_x64.dll .dll, ...) failed.
process_begin: CreateProcess(NULL, basename rx_073eb8c6cf7abc1492df4aa0ca30126b_x64.dll .dll, ...) failed.
"zrx_073eb8c6cf7abc1492df4aa0ca30126b_x64.o" was unexpected at this time.
make: *** [rx_073eb8c6cf7abc1492df4aa0ca30126b_x64.dll] Error 255


error building model
gcc  -I"C:/PROGRA~1/R/R-42~1.0/include" -DNDEBUG     -I"c:/rtools42/x86_64-w64-mingw32.static.posix/include"  -O3  -I"C:\Users\Ziran\AppData\Local\R\WIN-LI~1\4.2\rxode2\include"   -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c rx_073eb8c6cf7abc1492df4aa0ca30126b_x64.c -o rx_073eb8c6cf7abc1492df4aa0ca30126b_x64.o


C:/PROGRA~1/R/R-42~1.0/etc/x64/Makeconf:274: warning: overriding commands for target `.m.o'
C:/PROGRA~1/R/R-42~1.0/etc/x64/Makeconf:267: warning: ignoring old commands for target `.m.o'
process_begin: CreateProcess(NULL, basename rx_073eb8c6cf7abc1492df4aa0ca30126b_x64.dll .dll, ...) failed.
process_begin: CreateProcess(NULL, basename rx_073eb8c6cf7abc1492df4aa0ca30126b_x64.dll .dll, ...) failed.
process_begin: CreateProcess(NULL, basename rx_073eb8c6cf7abc1492df4aa0ca30126b_x64.dll .dll, ...) failed.
"zrx_073eb8c6cf7abc1492df4aa0ca30126b_x64.o" was unexpected at this time.
make: *** [rx_073eb8c6cf7abc1492df4aa0ca30126b_x64.dll] Error 255





-----原始邮件-----
发件人:"Matthew Fidler" ***@***.***>
发送时间:2022-06-16 06:33:03 (星期四)
收件人: nlmixr2/rxode2 ***@***.***>
抄送: 1osde ***@***.***>, Author ***@***.***>
主题: Re: [nlmixr2/rxode2] error building model (Issue #214)



Could tou post a reproducible example so I can help you?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>


--

顺颂时祺 | With kind regards,
...................................................................


李自然｜Ziran Li
复旦大学附属华山医院 | Department of pharmacy, Huashan Hospital, Fudan University 
E-mail: ***@***.***

**Comment by billdenney** [comment]
@1osde , I just tried it on my system (Windows 10), and I didn't have any issues.

Can you please try reinstalling rxode2 with its dependencies the following command to see if it works then:

`install.packages(c("rxode2", "nlmixr2data", "lotri", "nlmixr2extra"))`

**Comment by 1osde** [comment]
Denney,


Thank you so much. I have solved the problem by reinstalling Rtools.


Thanks a lot 

Best wishes 
-----原始邮件-----
发件人:"Bill Denney" ***@***.***>
发送时间:2022-06-16 09:23:51 (星期四)
收件人: nlmixr2/rxode2 ***@***.***>
抄送: 1osde ***@***.***>, Mention ***@***.***>
主题: Re: [nlmixr2/rxode2] error building model (Issue #214)



@1osde , I just tried it on my system (Windows 10), and I didn't have any issues.

Can you please try reinstalling rxode2 with its dependencies the following command to see if it works then:

install.packages(c("rxode2", "nlmixr2data", "lotri", "nlmixr2extra"))

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>


--

顺颂时祺 | With kind regards,
...................................................................


李自然｜Ziran Li
复旦大学附属华山医院 | Department of pharmacy, Huashan Hospital, Fudan University 
E-mail: ***@***.***

**Comment by mattfidler** [comment]
Glad to hear!

**Comment by billdenney** [comment]
The current version of R (4.2.1) is recommend.  Can you please also try reinstalling RTools?
