### ISSUE TITLE
loglik functions for focei-type likelihoods

### ISSUE THREAD

**Issue by mattfidler** [nlmixr2/rxode2#216]

**Comment by billdenney** [comment]
Is it possible to make this work for other estimation methods, too?  I realize that it may not work for everything (for example, I doubt that it would work for nlme), but can it be generalized beyond the forcei family?

**Comment by billdenney** [comment]
Got it.  I wasn't trying to put the cart before the horse, and thanks for letting me know.  (But, I also always think that if the cart and horse can go together that they should.)

**Comment by mattfidler** [comment]
`focei` needs are different, they need a gradient.  Since `focei` runs alot of the `nlmixr2` object it needs to be first.

**Comment by mattfidler** [comment]
Well second, simulations and support in the `ui`  needed to be first, and it is already there 😉
