### ISSUE TITLE
Feature (un)request: Remove .rxWithSink and .rxWithSinkBoth

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/rxode2#22]
.rxWithSink and .rxWithSinkBoth seem like testing helper functions that may be possible to write without requiring these functions.

**Comment by mattfidler** [comment]
If I remember correctly, these also work with `REprintf` in rxode C. Because of parallel processing you have you use this function so the whole system doesnt crash.  But I coupd be forgetting here.

If that is the case I dont want to remove them.  Otherwise I have no problem moving it elsewhere...

**Comment by billdenney** [comment]
I'm gonna try rewriting them using `capture.output()` (part of base R).  `capture.output()` uses `sink()` internally, and I think that it generally does what you're looking for.  If you know of an issue with `capture.output()`, then we can keep these.

**Comment by mattfidler** [comment]
Yes.  It doesnt capture reprintf.  Other than that no issue

**Comment by mattfidler** [comment]
Let me look further and test some items and I will let you know.

**Comment by mattfidler** [comment]
These are fine to replace if you wish.

**Comment by mattfidler** [comment]
For now it stays
