### ISSUE TITLE
Load Failure with $ syntax

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/rxode2#24]
This line gives an error when run automatically but not when run manually.  Could there be a race condition for creating or deleting the file?  (Putting `Sys.sleep(1)` just above it didn't fix the problem.)

https://github.com/nlmixr2/rxode2/blob/26e5845e4a515b8e33a6a8ef956079cd9db00477/tests/testthat/test-load.R#L42

This is with the current github version on Windows.

**Comment by mattfidler** [comment]
I'm assuming this is fixed

**Comment by billdenney** [comment]
I just ran it manually on windows with the current main branch (20056e2b71f7fe8092f7687259152ad3ec92e1ea), and it still has an issue.

```
-- Failure (test-load.R:40:3): loading and unloading works. --------------------
file.exists(dll) is not TRUE

`actual`:   FALSE
`expected`: TRUE 

-- Failure (test-load.R:46:3): loading and unloading works. --------------------
file.exists(dll) is not TRUE

`actual`:   FALSE
`expected`: TRUE 

-- Failure (test-load.R:49:3): loading and unloading works. --------------------
file.exists(dll) is not TRUE

`actual`:   FALSE
`expected`: TRUE 


[ FAIL 3 | WARN 0 | SKIP 0 | PASS 17 ]
```

The way that I ran it was:

1. Pull current head
2. `devtools::load_all()`
3. `testthat::test_file("../tests/testthat/test-load.R")`

When run by executing each test sequentially (replace step 3 with pasting the contents of `test-load.R` into the R console), it succeeds.

**Comment by mattfidler** [comment]
There is a time delay in windows sometimes for releasing DLLs.  Perhaps that is He issue...?

**Comment by mattfidler** [comment]
Seems to work
