### ISSUE TITLE
Windows error with test-npde-mac.R

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/rxode2#25]
I get the following error when I run test-npde-mac.R on Windows 10.

```
== Testing test-npde-mac.R =====================================================
[ FAIL 0 | WARN 0 | SKIP 0 | PASS 0 ]Assertion failed!

Program: C:\PROGRA~1\R\R-41~1.2\bin\x64\Rterm.exe
File: C:/Users/Bill Denney/Documents/R/win-library/4.1/RcppEigen/include/Eigen/src/Core/PlainObjectBase.h, Line 285

Expression: (!(RowsAtCompileTime!=Dynamic) || (rows==RowsAtCompileTime)) && (!(ColsAtCompileTime!=Dynamic) || (cols==ColsAtCompileTime)) && (!(RowsAtCompileTime==Dynamic && MaxRowsAtCompileTime!=Dynamic) || (rows<=MaxRowsAtCompileTime)) && (!(ColsAtCompileTime==Dynamic && MaxColsAtCompileTime!=Dynamic) || (cols<=MaxColsAtCompileTime)) && rows>=0 && cols>=0 && "Invalid sizes when resizing a matrix or array."

Exited with status 3.
```

**Comment by mattfidler** [comment]
This is likely a memory issue, that is not enough memory is able to be allocated in the system, which causes this issue in windows.  It was chose because it was a highly memory intensive problem.

**Comment by billdenney** [comment]
The system I was using has 16GB RAM (I think-- I'm not on it right now).  That said, I've had memory exhaustion due to 32-bit processes being used when they should have been 64-bit.

Is there a way that you can think of to give a clear "ran out of memory" error?  That seems like it would be a preferred way to close this.  If not, we could just skip the test on Windows.

**Comment by mattfidler** [comment]
Unfortunately, there is no easy way.  I have attempted many times.

**Comment by billdenney** [comment]
This test is now skipped when there is not enough memory on Windows.  That's likely sufficient for now.
