### ISSUE TITLE
Feature Request: Function to set all random effects to zero in a model

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/rxode2#263]
I relatively often want to run simulations of the average subject to illustrate a feature of the model.  It would be helpful to have a function that would set all random effects and residual error to zero in a model.  The function itself would be pretty simple (go into $iniDf, set all estimates for any etas to 0).

Would this be of interest?  If so, I think that the interface would be something like:

```
zeroRe(model, which=c("omega", "sigma"))
```

(I'm suggesting the name and copying the interface from the `mrgsolve::zero_re()` function.)

**Comment by mattfidler** [comment]
It could be useful, though I would not likely be able to remember `zeroRe()`.  We already have `predict()` in `nlmixr2` do something perhaps simply piping to `predict` would be sufficient?

**Comment by mattfidler** [comment]
Think this was already added.
