### ISSUE TITLE
test-rm-dll.R works every other time that it is run

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/rxode2#27]
When I run test-rm-dll.R, it succeeds every other time (first time, success; second time, failure; third time, success...).

That suggests to me that it needs some additional clean-up of some type.  @mattfidler, can you suggest the right clean-up to add?

**Comment by billdenney** [comment]
This may be related to #24

**Comment by mattfidler** [comment]
I think there is some lag time between seeing the files on windows especially. Linux/Max/Solaris doesn't seem to have the same issue...

**Comment by mattfidler** [comment]
I assume this works.
