### ISSUE TITLE
Feature request: `as.function()` methods

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/rxode2#273]
Related to #271, I think it would help to have `as.function()` methods for `rxUi` (here in `rxode2`) and `nlmxir2FitCore` (in `nlmixr2est`) objects.  I think that they would just grab `x$fun` and `x$ui$fun`.  Would those be of interest if I took on making them?

**Comment by mattfidler** [comment]
If you want rhem I think it just fine

**Comment by billdenney** [comment]
I had a thought this morning:  These functions could be the way that we get the `; label()` on the same line when printing.  We can add a `srcref` attribute when using the `as.function()` methods.

**Comment by billdenney** [comment]
Thanks!
