### ISSUE TITLE
Unclear Purpose for test-zzzz-rxUse.R

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/rxode2#29]
It looks like test-zzzz-rxUse.R builds a package around a model.  Is that a necessary test?  It fails on Windows 10.

(The underlying question is that I'm uncertain of why `rxUse()` exists.  And the next question is if/how we should test it.)

**Comment by mattfidler** [comment]
`rxUse` allows `rxode2` models to be packaged as libraries of pre-compiled models, like this:

https://github.com/nlmixrdevelopment/rxModels

So if you compile a `roxde2` model (not ui at this point) then you can save it and the build process will compile and link against `rxode2`

So... building a package does make sense in this case, It think.

**Comment by billdenney** [comment]
Ah, okay.  That makes sense.  The test succeeds on Linux but fails on Windows.  I'll look into it a bit more, but I may end up skipping it on Windows.
