### ISSUE TITLE
CRAN request

### ISSUE THREAD

**Issue by mattfidler** [nlmixr2/rxode2#295]
- Fix segfaults on M1 macs and fedora
- Reduce the compilation time

**Comment by mattfidler** [comment]
Reducing the compilation time would probably be done by splitting the package into parts at this point....

**Comment by billdenney** [comment]
Is there a simpler solution to reduce compilation time by using `-O0`?  (Or at least a temporary solution to that end?)  I'm guessing that CRAN already uses MAKEFLAGS with `-j###` to parallelize compilation, but if not, is that possible?

**Comment by mattfidler** [comment]
- Moved out log-likilihood to `rxode2ll`

**Comment by mattfidler** [comment]
My guess is the segfault came from incompatible binaries.  For now I am closing this issue, and waiting for `rxode2ll` to hit CRAN.  Once that is done I can try to test with the `rhub` fedora image.
