### ISSUE TITLE
Issue with switch away from environments

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/rxode2#310]
While testing babelmixr2, the following line causes an error:

https://github.com/nlmixr2/rxode2/blob/6b14e831b8e38f6571adcf617c667b6397266ec0/R/ui-getControl.R#L63

**Comment by mattfidler** [comment]
I havent to babelmixr2 yet.  While I could supply a fix I want to make sure that I can catch where the UIs are being generated or changed in  babelmixr2 first
