### ISSUE TITLE
Low Priority Feature Request: Push all output into messages with normal model compilation

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/rxode2#34]
I'm currently trying to make successful testing closer to silent (PR coming).  With that, I found that `suppressMessages()` does captures everything but a few line feeds, and I don't see how to suppress those line feeds in a simple way.  I think that this could be Windows- or Rstudio-specific.

A specific example where this occurs would be:

```r
norm <- rxode2("
d/dt(y)  = dy
d/dt(dy) = mu*(1-y^2)*dy - y
## Initial conditions
y(0) = 2
dy(0) = 0
## mu
mu = 1 ## nonstiff; 10 moderately stiff; 1000 stiff
")
  jac <- norm
  jac <- suppressMessages(rxode2(jac, calcJac = TRUE))
```

I expected the final line to have no output, but there is an empty line generated.

I think that this may be related to progress bars and possibly this line:

https://github.com/nlmixr2/rxode2/blob/24208715c5b07f2c16fd83b665eae01b46805f47/src/par_solve.cpp#L346

**Comment by billdenney** [comment]
This only happens when running interactively in Rstudio (not in non-interactive mode in Windows or at all in Linux), so I don't think it's a real issue.

**Comment by mattfidler** [comment]
This is an easy fix (I think).  It simply shows I don't use RStudio often.
