### ISSUE TITLE
Feature request: allow insertion of a parameter after a specified parameter in the ini block

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/rxode2#352]
When piping in new parameters, they are (mostly) inserted at the end of the parameter list.  The order of parameters can make the reporting table easier to interpret.

I think it would be helpful to have an ordering parameter to the code to pipe a new parameter in the ini block.  Does that seem useful?

**Comment by mattfidler** [comment]
It could be useful for this use case, though I think the use-case is pretty niche.
