### ISSUE TITLE
Move `test-lincmt-parse.R` to rxode2parse

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/rxode2#361]
`lincmt-parse` could possibly be ported to the `rxode2parse` package since that is where the parsing actually occurs and will boost its coverage.

_Originally posted by @mattfidler in https://github.com/nlmixr2/rxode2/issues/359#issuecomment-1304884698_

**Comment by billdenney** [comment]
It's not clear to me how to port the test to `rxode2parse`.  The first try I made was to simply replace the `rxode2()` calls with `rxode2parse()` calls, but they didn't give errors when I (or the tests) expected them.

**Comment by mattfidler** [comment]
Its not so easy...hence I didnt move it.  I have to study the code again to
figure it out.  This is where the parsing occurs though.
