### ISSUE TITLE
Currently this is not possible, but perhaps in the future.  Something like `model(..., append=lhs_variable)` and it will append after the first occurrence of `lhs` variable

### ISSUE THREAD

**Issue by mattfidler** [nlmixr2/rxode2#366]
Currently this is not possible, but perhaps in the future.  Something like `model(..., append=lhs_variable)` and it will append after the first occurrence of `lhs` variabe

_Originally posted by @mattfidler in https://github.com/nlmixr2/rxode2/discussions/271#discussioncomment-4258140_

**Comment by mattfidler** [comment]
Note #365.

The append variable would probably have to be parsed inside each call, otherwise the `NSE` will likely not work.

**Comment by billdenney** [comment]
This is related to (but not the same as) #352.
