### ISSUE TITLE
Low Priority Feature request: See if et() can be sped up

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/rxode2#37]
When running the random number testing, this line takes longer than it seems like would be required.  So, I think it would be good to see if it could be sped up (without making code unreadable).

I'll take this on at some point.

```r
library(rxode2)
ev <- et(1, id = 1:70000)
```

**Comment by billdenney** [comment]
With quick profiling, I found 2 things:

* When `id=10000`, it goes much faster than when `id=70000`
* The time is all spent in `.Call(`_rxode2_et_`, .lst, list())` (https://github.com/nlmixr2/rxode2/blob/24208715c5b07f2c16fd83b665eae01b46805f47/R/et.R#L604), so I won't be able to fix it.

Given the low priority for this. I will close it.

**Comment by mattfidler** [comment]
This is true.  It has to do with sorting.  It currently resides in C/C++ fyi
