### ISSUE TITLE
Possibly lost memory during nlmixr2extra valgrind

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/rxode2#398]
While trying to track down the issues with nlmixr2extra CI, I ran valgrind on it locally, and I found the following that may be an issue:

https://github.com/billdenney/nlmixr2CRANtesting/blob/19b36e211f92494d37a8ffbbcba6db673867f3cb/outputs/nlmixr2extra_test_valgrind.txt#L4482-L4497

All of the other possibly lost data did not appear to be related to nlmixr2/rxode2.

**Comment by mattfidler** [comment]
These often occur when using threads, but will not occur when using non-threads.  I believe it is a false positive (though CRAN may get picky about these).

**Comment by mattfidler** [comment]
You can see the parallelization problems with 

https://github.com/billdenney/nlmixr2CRANtesting/blob/19b36e211f92494d37a8ffbbcba6db673867f3cb/outputs/nlmixr2extra_test_valgrind.txt#L4488-L4490

The OMP parallel is allocating memory which may be lost.  Hence, it isn't actually in `rxode2`.

Joe may be trying to move this to `RcppParallel` as well, so I am not concerned with this currently.

**Comment by billdenney** [comment]
If it's not worth fixing, feel free to close the issue (... as you just did 😄 ).  I'm trying to track down where the issue arises in nlmixr2extra.

**Comment by mattfidler** [comment]
If you are brave you can try `gcTorture()` which is where I believe the error may be revealed.

**Comment by billdenney** [comment]
I'm extra brave!  I'm running `gcTorture()` and `valgrind` at the same time.  I'll let you know what happens in 2024.
