### ISSUE TITLE
Simplify dataset and event documentation

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/rxode2#4]
Currently, dataset and event documentation is covered in several different locations.  I think that it would be better to simplify these into fewer locations (possibly one datasets and events vignette, to become a chapter in the user's manual):

* https://github.com/nlmixr2/rxode2/blob/main/vignettes/events-classic.Rmdh
    * https://github.com/nlmixr2/rxode2/blob/main/vignettes/events-et.Rmdh
* https://github.com/nlmixr2/rxode2/blob/main/vignettes/rxode2-datasets.Rmd
* https://github.com/nlmixr2/rxode2/blob/main/vignettes/rxode2-event-table.Rmd
* https://github.com/nlmixr2/rxode2/blob/main/vignettes/rxode2-event-types.Rmd
    * https://github.com/nlmixr2/rxode2/blob/main/vignettes/rxode2-event-types.Rmdh
* https://github.com/nlmixr2/rxode2/blob/main/vignettes/rxode2-events-classic.Rmd
* https://github.com/nlmixr2/rxode2/blob/main/vignettes/rxode2-datasets.Rmd
* https://github.com/nlmixr2/rxode2/blob/main/vignettes/rxode2-data-frame.Rmd
    * https://github.com/nlmixr2/rxode2/blob/main/vignettes/df.Rmdh

**Comment by mattfidler** [comment]
The chapters are pulled from here, though I haven't rebuilt them yet.

**Comment by mattfidler** [comment]
I accidentally "unwatched" this repository
