### ISSUE TITLE
Switch Default Branch on Codecov.io

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/rxode2#40]
Currently, I think that the default branch on codecov.io is "master" when it should be "main".  That will fix the badge image at the top of the Readme.md file.  (The same is appears to be needed for lotri and nlmixr2.)

To make the change, go to https://app.codecov.io/gh/nlmixr2/rxode2/settings and then change the default branch to main.  (I think that should work; that's how it looks in a different repo for me.)

**Comment by mattfidler** [comment]
Nope it is main:

![image](https://user-images.githubusercontent.com/514778/150836628-0fd986a0-1b9b-48b4-943d-3670043cbd07.png)

**Comment by mattfidler** [comment]
Likely the icon is wrong
