### ISSUE TITLE
test-lincmt-solve with seq(0.5, 1, 1.5) only uses a single value

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/rxode2#41]
There are 6 loops in `test-lincmt-solve.R` that have `seq(0.5, 1, 1.5)` where the result is that the value is only 0.5.  I think that the intent is to use `c(0.5, 1, 1.5)`.  @mattfidler, can you please take a look and confirm that `c()` is the intent?

https://github.com/nlmixr2/rxode2/blob/2908fc9e128863178329e089dd43fc4917943905/tests/testthat/test-lincmt-solve.R#L1678
https://github.com/nlmixr2/rxode2/blob/2908fc9e128863178329e089dd43fc4917943905/tests/testthat/test-lincmt-solve.R#L1709
https://github.com/nlmixr2/rxode2/blob/2908fc9e128863178329e089dd43fc4917943905/tests/testthat/test-lincmt-solve.R#L1739
https://github.com/nlmixr2/rxode2/blob/2908fc9e128863178329e089dd43fc4917943905/tests/testthat/test-lincmt-solve.R#L1771
https://github.com/nlmixr2/rxode2/blob/2908fc9e128863178329e089dd43fc4917943905/tests/testthat/test-lincmt-solve.R#L1799
https://github.com/nlmixr2/rxode2/blob/2908fc9e128863178329e089dd43fc4917943905/tests/testthat/test-lincmt-solve.R#L1829

**Comment by mattfidler** [comment]
It is likely a `c` was the intent.
