### ISSUE TITLE
test-lincmt-solve.R crashes in Windows after test 252

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/rxode2#42]
Running `test-lincmt-solve.R` on Windows (but not on Linux) crashes after test 252.  I cannot isolate the issue.

When I run the test manually, I sometimes get a crash after this line (below), but other times, there is no crash.

https://github.com/nlmixr2/rxode2/blob/2908fc9e128863178329e089dd43fc4917943905/tests/testthat/test-lincmt-solve.R#L58

Running the tests automatically (`devtools::test()`) reliably crashes after test 252 in `test-lincmt-solve.R`.

Given some of your previous statements, my guess is that there is some form of race on dll creation/deletion.

**Comment by mattfidler** [comment]
This seems to be a similar issue as #25 

Here is the error I am getting:

```
/ |       264 | lincmt-solve                                                    Assertion failed!

Program: c:\R\R-4.1.1\bin\x64\Rterm.exe
File: C:/R/R-4.1.1/library/RcppEigen/include/Eigen/src/Core/PlainObjectBase.h, Line 285

Expression: (!(RowsAtCompileTime!=Dynamic) || (rows==RowsAtCompileTime)) && (!(ColsAtCompileTime!=Dynamic) || (cols==ColsAtCompileTime)) && (!(RowsAtCompileTime==Dynamic && MaxRowsAtCompileTime!=Dynamic) || (rows<=MaxRowsAtCompileTime)) && (!(ColsAtCompileTime==Dynamic && MaxColsAtCompileTime!=Dynamic) || (cols<=MaxColsAtCompileTime)) && rows>=0 && cols>=0 && "Invalid sizes when resizing a matrix or array."
```

There are a few issues in this:

- There are assertions within the code base, which will remove us from CRAN after submission
- The stan base for `linCmt` is likely changed enough that our code sometimes causes issues in windows, but no other platform. 

If you have more memory, this may not occur.  It also states that the focei with `linCmt` is very memory intensive.

**Comment by billdenney** [comment]
Is this due to compiler optimization?  If so, is it possible/reasonable to use the no-optimization compiler flag (`-O0`, I think), if there is not enough RAM?  I don't quite know what "not enough" is, but I'm guessing <16GiB based on the system I'm testing with.

**Comment by mattfidler** [comment]
I don't think so.  I think it has to do with compiling flags. 

https://github.com/nlmixrdevelopment/RxODE/pull/460

is the relevant discussion.  The flags make it very difficult to install `RxODE`, so they gave up.

**Comment by mattfidler** [comment]
Windows seems to be the problem that keeps resurfacing with the stan headers.  Windows is the only reason why we bumped the  required R version to 4.0 because the windwos toolchain could no longer compile the stan pieces of rxode. A possible way to do this is to break of the stan pieces into their own stand-alone package.  This would be alot of work, but would make maintenance easier in the long run I think.

**Comment by mattfidler** [comment]
Hm.  It could be a memory issue...  I only say this because it solves in windows under their test environment.

**Comment by billdenney** [comment]
I've been thinking about this a bit more...

Do we know when the memory issue happens?  I would guess that it has two times that it could occur.  Once during compilation and once during calculation/integration.  Is it possible to add a message just before compilation and just before integration starts so that we could diagnose its timing?

If it happens during compilation, that seems like something we should raise an upstream issue about-- perhaps with Rcpp?  And, hopefully they could catch it.  If it happens during integration, I don't know what the right solution would be, but is there a way that we could start to isolate it to a smaller block of code?

**Comment by mattfidler** [comment]
It occurs during calculation. The problem with isolating it is that different memory is available in different systems, which means the error will occur in different places.  I isn't clear how much memory you would need above what `rxode2` already calculates.  It could also change when `eigen` or `stan` changes, so that is risky too.  

I don't know of a good way to catch this early.

**Comment by mattfidler** [comment]
Closing cor nkw
