### ISSUE TITLE
Is `ini.rxModelVars` necessary?

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/rxode2#420]
I don't know when the rxModelVars object would exist to need the `ini.rxModelVars` function.  But, the function doesn't work right now.  The underlying issue appears to be that the ... argument is not being searched upstream from `ini.function`.  But, rather than update non-working code to work, it seems like the better path would be to remove unused code.

(I found this while trying to bring `piping-ini.R` up to 100% code coverage.)

``` r
library(rxode2)
#> rxode2 2.0.11.9000 using 8 threads (see ?getRxThreads)
#>   no cache: create with `rxCreateCache()`
mod <- function() {
  ini({
    a <- 1
    b <- 2
    c <- 3
    d ~ 1
    h ~ 2
    addSd <- 2
  })
  model({
    b <- a + b*log(c)
    f <- a + d + e
    i <- j + h
    b ~ add(addSd)
  })
}
ini(rxModelVars(mod), a <- 2)
#> ℹ parameter labels from comments are typically ignored in non-interactive mode
#> ℹ Need to run with the source intact to parse comments
#> Error in eval(.bracketExpression, envir = envir): ..1 used in an incorrect context, no ... to look in
```

<sup>Created on 2023-01-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
```

**Comment by mattfidler** [comment]
Well, if we take it out the support for `rxModelVars` it would be inconsistent with the rest of `rxode2`.  

Still, I took out the method and used the new method `as.rxUi` in the `ini.default()` instead.  It should still work in a majority of cases.241116
