### ISSUE TITLE
Changing a parameter label change a fit model to an rxUi object

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/rxode2#422]
I think that changing a label should retain the fit estimates and object.

``` r
library(nlmixr2)
#> Loading required package: nlmixr2data

one.compartment <- function() {
  ini({
    tka <- 0.45; label("Ka")
    tcl <- 1; label("Cl")
    tv <- 3.45; label("V")
    eta.ka ~ 0.6
    eta.cl ~ 0.3
    eta.v ~ 0.1
    add.sd <- 0.7
  })
  model({
    ka <- exp(tka + eta.ka)
    cl <- exp(tcl + eta.cl)
    v <- exp(tv + eta.v)
    d/dt(depot) = -ka * depot
    d/dt(center) = ka * depot - cl / v * center
    cp = center / v 
    cp ~ add(add.sd)
  })
}

fit <- nlmixr(one.compartment, theo_sd, est="focei",
              control=list(print=0), 
              table=list(npde=TRUE, cwres=TRUE))
#> rxode2 2.0.11.9000 using 8 threads (see ?getRxThreads)
#>   no cache: create with `rxCreateCache()`
#> calculating covariance matrix
#> done
#> → Calculating residuals/tables
#> ✔ done
#> → compress origData in nlmixr2 object, save 5952
#> → compress parHist in nlmixr2 object, save 2416

fit %>%
  ini(
    tka <- label("Absorption rate")
  )
#>  ── rxode2-based free-form 2-cmt ODE model ────────────────────────────────────── 
#>  ── Initalization: ──  
#> Fixed Effects ($theta): 
#>       tka       tcl        tv    add.sd 
#> 0.4697670 1.0102406 3.4617013 0.6958761 
#> 
#> Omega ($omega): 
#>           eta.ka     eta.cl      eta.v
#> eta.ka 0.3901399 0.00000000 0.00000000
#> eta.cl 0.0000000 0.06699891 0.00000000
#> eta.v  0.0000000 0.00000000 0.01887332
#> 
#> States ($state or $stateDf): 
#>   Compartment Number Compartment Name
#> 1                  1            depot
#> 2                  2           center
#>  ── μ-referencing ($muRefTable): ──  
#>   theta    eta level
#> 1   tka eta.ka    id
#> 2   tcl eta.cl    id
#> 3    tv  eta.v    id
#> 
#>  ── Model (Normalized Syntax): ── 
#> function() {
#>     ini({
#>         tka <- 0.46976695148739
#>         label("Absorption rate")
#>         tcl <- 1.01024057972991
#>         label("Cl")
#>         tv <- 3.46170130602243
#>         label("V")
#>         add.sd <- c(0, 0.695876121480103)
#>         eta.ka ~ 0.390139900793204
#>         eta.cl ~ 0.0669989064330149
#>         eta.v ~ 0.0188733157599625
#>     })
#>     model({
#>         ka <- exp(tka + eta.ka)
#>         cl <- exp(tcl + eta.cl)
#>         v <- exp(tv + eta.v)
#>         d/dt(depot) = -ka * depot
#>         d/dt(center) = ka * depot - cl/v * center
#>         cp = center/v
#>         cp ~ add(add.sd)
#>     })
#> }
```

<sup>Created on 2023-01-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mattfidler** [comment]
Possibly.

If so this belongs in `nlmixr2est`

**Comment by billdenney** [comment]
But, it seems like it should work for any type of input (rxUi or various nlmixr2FitCore types).  That seems like a modification in `rxode2` is the right place for it (unless I'm missing something).  But, perhaps the generic would need to occur on the ui part, only, for labels (and returning the `rxUi` object if something more substantial than a label was changed).

**Comment by mattfidler** [comment]
Ok.  It is returning a `rxUi` object.  I thought you meant update the fit...

The reprex shows it (it isn't a function).

**Comment by billdenney** [comment]
Sorry that I wasn't clear.

**Comment by billdenney** [comment]
And, no, I don't think that it should update the fit.  But, if no new fit is needed, then it should keep the fit is the idea.  The two times when no new fit is needed should be parameter reordering and label changes.  I think that everything else should remove the fit and keep only the rxUi.

**Comment by mattfidler** [comment]
The fit object has `fit$ui` embedded in the environment.  

Reordering the columns of the fit parameters takes a bit more code and still needs to modify the fit object, while technically only re-ordering and re-labeling a few pieces within it.  

If this is the intent, this is what I think:

- Perhaps it should return an updated fit object (or update the fit object like `addCwres()` to be consistent.
- Be turned off somehow because it is not entirely obvious that this would occur since it seems that every other time it simply returns a `rxUi` object.
- Track if only the labels and parameter order has changed while keeping the environment handy for updating (which will update the fit object, unless you clone it.  
- Update all the tables (I think there are 2)
- Update the ini object.

Overall it will probably need to be split up over both packages.

Though I could still be mis-understanding what you wish to do here...

**Comment by billdenney** [comment]
For now, let's let it be.  If someone wants to change something after the fit, then maybe they just need to rerun the model.
