### ISSUE TITLE
rxTest of par-solve results in missing symbol

### ISSUE THREAD

**Issue by joecodemonkey** [nlmixr2/rxode2#435]
After grabbing the latest rxode2, running:

`rxTest("par-solve")`

eventually results in:

`rxode2.so: undefined symbol: _rxode2_addLine`

It appears that addLine was possibly removed from rxode2, but still referenced from rxode2 and is in other lmixr2 libraries.

**Comment by mattfidler** [comment]
It isn't in this repository any more, but should be copied here on setup with the following code run on setup:

https://github.com/nlmixr2/rxode2/blob/a21d627fd5059e009e189199b95dac3c71ade7cf/inst/tools/workaround.R#L97-L101

To me, this means that the libraries are out of sync.  

To fix that, try:
```r
#install.packages("remotes") # if needed
remotes:install_github("nlmixr2/dparser-R")
remotes:install_github("nlmixr2/lotri")
remotes:install_github("nlmixr2/rxode2parse") # where the _rxode2_addLine code is
remotes:install_github("nlmixr2/rxode2ll") # probably doesn't need to be reinstalled
remotes::install_github("nlmixr2/rxode2random")
remotes::install_github("nlmixr2/rxode2et")
```

Once these are setup, the development version of `rxode2` should be able to be set up.

**Comment by mattfidler** [comment]
You could also manually copy the file, though it seems that shouldn't be required.  If you do remove the `_goodFuns` line as in the setup code.

**Comment by joecodemonkey** [comment]
By copying sbuf.c from nonmem2rx the issue is resolved.

**Comment by mattfidler** [comment]
Let me know if you need anything else.
