### ISSUE TITLE
Event Table issue 

### ISSUE THREAD

**Issue by BrettMartini** [nlmixr2/rxode2#438]
Hi! I am familiarizing myself with the rxode2 package and was using the Weight based dosing (section 12.4) example found in the [rxode2 ](https://nlmixr2.github.io/rxode2-manual/examples.html#weight-based-dosing) user manual. I keep running into the error in the picture when running the code and have tried to uninstall and reinstall the package without success. Is there a work around for this? I would like to eventually adapt this code for my own use. Thank you for the help! 

<img width="352" alt="error" src="https://user-images.githubusercontent.com/122819333/219478395-8c5bc3c1-80c8-4e1d-ba5c-279a4c45f8ca.png">

* Apologies in advance if this is the wrong location to ask questions about errors with the package.

**Comment by billdenney** [comment]
Hi @BrettMartini, thanks for your interest, and yes, this is the right place to ask questions like this.

I just ran the examples on my local system, and I didn't have any errors.  Can you please share how you tried to uninstall and reinstall the packages?  The two questions I'm getting to here are:

1. Did you install the development version or the CRAN version?
2. Did you reinstall each of the `rxode2` dependencies?

My first guess is that the `rxode2` dependencies are out of sync with the main `rxode2` package on your system.

**Comment by BrettMartini** [comment]
Hi @billdenney. Thank you for the help! I have the CRAN version of R installed.  I did not think to reinstall the dependencies, but this fixed the problem immediately. Thank you again!

**Comment by billdenney** [comment]
Great!

**Comment by mattfidler** [comment]
Thanks @billdenney 

Just a note that importing event tables is not needed (and hasn't been for a long time), you can run directly on the data and it won't drop your covariate information like the importing of the event table does.
