### ISSUE TITLE
`ini()` doesn't warn on some types of invalid input

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/rxode2#439]
I just noticed that `ini()` doesn't warn when the input is a formula.  We likely need to think about how to make it accurately warn when the input is invalid in some way.

The underlying issue comes from the fact that there is no `else` here:

https://github.com/nlmixr2/rxode2/blob/136e8bb1cf39d39e1f024277579915cb8267cbaf/R/piping-ini.R#L448

I found this due to a regression in `nlmixr2lib::addEta()`.

Note in the example below that etalcl doesn't change to 0.1.

``` r
library(rxode2)
#> rxode2 2.0.11.9000 using 8 threads (see ?getRxThreads)
#>   no cache: create with `rxCreateCache()`
mod <- function () {
  ini({
    lka <- 0.45
    lcl <- 1
    lvc <- 3.45
    propSd <- c(0, 0.5)
    etalcl ~ 0.2
  })
  model({
    ka <- exp(lka)
    cl <- exp(lcl + etalcl)
    vc <- exp(lvc)
    cp <- linCmt()
    cp ~ prop(propSd)
  })
}
mod %>%
  ini(
    as.formula(etalcl ~ 0.1)
  )
#>  ── rxode2-based solved PK 1-compartment model with first-order absorption ────── 
#>  ── Initalization: ──  
#> Fixed Effects ($theta): 
#>    lka    lcl    lvc propSd 
#>   0.45   1.00   3.45   0.50 
#> 
#> Omega ($omega): 
#>        etalcl
#> etalcl    0.2
#>  ── μ-referencing ($muRefTable): ──  
#>   theta    eta level
#> 1   lcl etalcl    id
#> 
#>  ── Model (Normalized Syntax): ── 
#> function() {
#>     ini({
#>         lka <- 0.45
#>         lcl <- 1
#>         lvc <- 3.45
#>         propSd <- c(0, 0.5)
#>         etalcl ~ 0.2
#>     })
#>     model({
#>         ka <- exp(lka)
#>         cl <- exp(lcl + etalcl)
#>         vc <- exp(lvc)
#>         cp <- linCmt()
#>         cp ~ prop(propSd)
#>     })
#> }
mod
#> function () {
#>   ini({
#>     lka <- 0.45
#>     lcl <- 1
#>     lvc <- 3.45
#>     propSd <- c(0, 0.5)
#>     etalcl ~ 0.2
#>   })
#>   model({
#>     ka <- exp(lka)
#>     cl <- exp(lcl + etalcl)
#>     vc <- exp(lvc)
#>     cp <- linCmt()
#>     cp ~ prop(propSd)
#>   })
#> }
```

<sup>Created on 2023-02-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mattfidler** [comment]
I never actually meant for the above code to work, this is what is tested (and still works)

``` r
library(rxode2)
#> rxode2 2.0.11.9000 using 8 threads (see ?getRxThreads)
#>   no cache: create with `rxCreateCache()`
mod <- function () {
  ini({
    lka <- 0.45
    lcl <- 1
    lvc <- 3.45
    propSd <- c(0, 0.5)
    etalcl ~ 0.2
  })
  model({
    ka <- exp(lka)
    cl <- exp(lcl + etalcl)
    vc <- exp(lvc)
    cp <- linCmt()
    cp ~ prop(propSd)
  })
}
mod %>%
  ini(etalcl ~ 0.1)
#> ℹ change initial estimate of `etalcl` to `0.1`
#>  ── rxode2-based solved PK 1-compartment model with first-order absorption ────── 
#>  ── Initalization: ──  
#> Fixed Effects ($theta): 
#>    lka    lcl    lvc propSd 
#>   0.45   1.00   3.45   0.50 
#> 
#> Omega ($omega): 
#>        etalcl
#> etalcl    0.1
#>  ── μ-referencing ($muRefTable): ──  
#>   theta    eta level
#> 1   lcl etalcl    id
#> 
#>  ── Model (Normalized Syntax): ── 
#> function() {
#>     ini({
#>         lka <- 0.45
#>         lcl <- 1
#>         lvc <- 3.45
#>         propSd <- c(0, 0.5)
#>         etalcl ~ 0.1
#>     })
#>     model({
#>         ka <- exp(lka)
#>         cl <- exp(lcl + etalcl)
#>         vc <- exp(lvc)
#>         cp <- linCmt()
#>         cp ~ prop(propSd)
#>     })
#> }
```

<sup>Created on 2023-02-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mattfidler** [comment]
I guess it should either allow or error for the input instead of silently do nothing.

**Comment by billdenney** [comment]
That was my thought: it should either work or give an error, but it shouldn't be silent if it does nothing.

**Comment by billdenney** [comment]
Before resolving this, let's discuss what the desired behavior is exactly.  I generally think that whatever we decide should be along the lines of "this is easiest to use for the user and maintain for us."  To that end, I think that one of the following likely makes the most sense:

* Be generally permissive on input:
    * Allow language objects (as is currently done), convert strings to language objects via `str2lang()`, consider formulae to be like any other tilde operator as a language object (and convert them to be a call on input).  If it's not one of those, give a clear error.
* Be strict on input:
    * Only accept language objects, and give clear errors otherwise.
* Something else?

I lean toward the first because it's easiest for the user, and it allows simpler programming (send in a string of what you want to change is easier than sending in a language object).  But, I can understand the goals of the second.

Thoughts?

**Comment by mattfidler** [comment]
Strings too... 

Anything we add will add more to the maintenance burden, though as you said would be easier to use too.

I guess I am leaning to the ease of use too.

**Comment by billdenney** [comment]
I'm working on this, and checking for change detection is somewhat difficult.  What I'm really wanting to look for is "did the user provide valid input" rather than "did a change occur".

For example, if a user fixes a parameter that was already fixed, that seems like it's fine and it already gives a warning.

I think that the current (in the new PR) checks for everything, but I want to have an `else` that captures input that somehow made it through all the code without a change.  What I was just trying (locally, not yet in the PR) was making some of the functions have output arguments of `TRUE` when there is a change and `FALSE` when there is no change, but that is proving more difficult, too.

Question: @mattfidler, do you think that looking for valid input across all input types or changes is helpful?  Or, should I leave the PR as it now stands for input validation?

**Comment by mattfidler** [comment]
I was thinking at first to put this in `.quoteCallInfoLines`, but I think this is probably fine

**Comment by billdenney** [comment]
I agree that it seems like a better fit in `.quoteCallInfoLines`.  But also, `.quoteCallInfoLines` is a very dense function that does several different things, it seems.

I'm trying to make out how to insert the code I made in #442 into that function, and I don't see a good fit.  So, I'm trying to make a pre-processing function that can hopefully simplify things.  My first thought was that the preprocesser could possibly replace `.quoteExpandBracketsOrCs()` by expanding the arguments into a list and going from there, but that's appearing to be much more complex.

So, I'm taking a shot at it, but I may need some guidance to get through that part of the code.

**Comment by mattfidler** [comment]
I don't think it needs to, actually it already has a case for strings

https://github.com/nlmixr2/rxode2/blob/a21d627fd5059e009e189199b95dac3c71ade7cf/R/piping.R#L200

It simply needs one for a formula.  I think less is more. No need to refactor unless it is broken.

**Comment by mattfidler** [comment]
Something right here

https://github.com/nlmixr2/rxode2/blob/a21d627fd5059e009e189199b95dac3c71ade7cf/R/piping.R#L207

should be fine.  

And this is also where you can simply test for unhanded types.  Though most types are covered already.

I only see this formula case.

**Comment by mattfidler** [comment]
I just tried, piping strings in the `ini` actually works now without any modification.

**Comment by mattfidler** [comment]
I also tried if you provide a formula as a variable it does not work it only silently fails when you try:

```r
%>% ini(as.formula(a~b))
```

Which is really an idiom that many people may use.... 

Issue #445 fixes only that issue.  It could be used on the `model()` statement too, I guess.

Since it is mostly non-standard evaluation, I cannot check for types as easily as `inherits(x, "formula")`

**Comment by mattfidler** [comment]
What do you think @billdenney ? I'm assuming you were using `ini(as.formula())` for some reason.

**Comment by mattfidler** [comment]
Maybe still have an `else` expression here:

https://github.com/nlmixr2/rxode2/blob/136e8bb1cf39d39e1f024277579915cb8267cbaf/R/piping-ini.R#L448

**Comment by mattfidler** [comment]
Added. 

Also you used `cli::cli_abort` instead of `stop`.  While I don't mind it, I think the way of exiting should be consistent.  

Also I cannot call `cli::cli_abort`  as easily in `C`/`C++`, so I lean toward sticking with `stop`.  What do you think?

**Comment by mattfidler** [comment]
You could also look at the error descriptions and update them to be a bit more helpful, I'm unsure they are always that helpful.

**Comment by billdenney** [comment]
Thanks for this help!  Yes, I was using something like `ini(as.formula())`.  The reason was that I didn't know that I could pass in a string, and that was the way that I thought to put in the between-subject variability in the `addEta()` function.

**Comment by mattfidler** [comment]
I think you couldn't pass a string at the time I wrote this, but you asked for it probably because of the same function (but I obviously forgot).

Note, I am unsure if you should allow `addEta()` to be a `s3` method so that things like `nonmem2rx` could retain information outside a typical ui (like the dataset etc).

Currently piping maintains the extra nonmem information (like `sigma` for instance).  With `addEta()` this would be removed since it calls the `$fun()` method.

**Comment by billdenney** [comment]
You're right that the information is lost due to the `$fun()` call.  My first preference would be to use something better than `$fun()` to make the changes rather than making it S3.

I'm not averse to S3, but if there's a better way to do it, I'd prefer that.  My guess is that I could call `$fun()` to search for the information needed about parameters, and use that.  But also, I now know more about how to search and pipe models, so it may just be easier overall.

**Comment by mattfidler** [comment]
Simply remove the `$fun` and it wold retain whatever it needs to retain, actually.  But it would be a full rxode2 ui object (I'm unsure why you only wanted to return the function here).
