### ISSUE TITLE
nlmixr error (symengine-related?) when fitting a large qsp model

### ISSUE THREAD

**Issue by andreasmeid** [nlmixr2/rxode2#475]
Dear All,

I want to estimate a single parameter from a complex QSP model with nlmixr as a test, but I get the error message below. A first search points to symengine, but I really don't know what the problem might be. Where could the error be? Please find the objects as an RData-file attached as a zip.

Many thanks and best wishes

Andreas 

[example_files.zip](https://github.com/nlmixr2/nlmixr2/files/10992507/example_files.zip)
> load("example_files.RData")
> fit <- nlmixr2(qsp_model, potassium_data,  est="foce") 
> loading into symengine environment...
> pruning branches (`if`/`else`) of full model...
v done
Error in parse(text = paste0("quote({", .rxUnXi(.val2), "})")) : 
  <text>:1:14: unexpected 'in'
1: quote({Error in
                 ^
Error: <text>:1:14: unexpected 'in'
1: quote({Error in
                 ^

**Comment by mattfidler** [comment]
I believe the function `max` is not working currently in the symengine currently.

While I think it used to work, as a work-around all the `max(0, x)` can be relpaced by `ifelse(x>0, x, 0)`

**Comment by mattfidler** [comment]
Consistently going through the lines I am seeing:

```r
[[76]]
[1] "Error in max(0, (exp(-m_Na_ALDO * (Nain - norm_Na_intake)) - 1)) : \n  invalid 'type' (S4) of argument\n"
attr(,"class")
```

**Comment by mattfidler** [comment]
See:

https://github.com/nlmixr2/nlmixr2est/issues/261

**Comment by andreasmeid** [comment]
Dear Matt,

thank you very much, this seems to have been indeed problematic. I replaced the max function in the code of the attached file with the ifelse function. However, now I get a different error message that I cannot assign:

[example_files_wo_max.zip](https://github.com/nlmixr2/rxode2/files/10999817/example_files_wo_max.zip)


> fit <- nlmixr2(qsp_model_wo_max, potassium_data,  est="foce") #[which(potassium_data$ID %in% c(134432329, 85718607)),]
> loading into symengine environment...
> pruning branches (`if`/`else`) of full model...
v done
Error in get("rx_pred_", envir = .s) : object 'rx_pred_' not found
Error: object 'rx_pred_' not found

What might be the reason for this?

Many thanks and best wishes
Andreas

**Comment by mattfidler** [comment]
I haven't looked at the code yet, but one thing to quickly check is that you have the residual/endpoint specified.  For example:
```r
Cc ~ add(add.sd)
```

in the `model()` block and an estimate of `add.sd<-0.01` or something in the `ini()` block.

In theory this should be checked for so maybe it is something else.

**Comment by mattfidler** [comment]
I'm glad it helped you!  

I will close this for now, since the `max()`  `min()` and `abs()` is a known issue that needs to be fixed.  I also opened another issue about `nlmixr2`/`rxode2` not stopping  without a residual specification.
