### ISSUE TITLE
rxode2 compiled with rxode2parse with a different solving structure

### ISSUE THREAD

**Issue by luyckxn** [nlmixr2/rxode2#479]
There seems to be an issue with the current version of rxode2 available on CRAN.
After the installation from CRAN, when I load the package, I get:

Error: le chargement du package ou de l'espace de noms a échoué pour ‘rxode2’ :
.onLoad a échoué dans loadNamespace() pour 'rxode2', détails :
  appel : NULL
  erreur : rxode2 compiled with rxode2parse with a different solving structure
can try: install.packages('rxode2', type='source')

Thanks in advance!

**Comment by luyckxn** [comment]
No, it is not working (the continuous integration tests for package campsis with GitHub actions were also failing because of this issue).
Only installation from github is working: remotes::install_github(repo="nlmixr2/rxode2") -> OK

**Comment by mattfidler** [comment]
Thanks @billdenney

**Comment by mattfidler** [comment]
This will likely be fixed whenever CRAN thinks that `rxode2` is ready.  It also breaks `nlmixr2est`.  I am waiting for a reply from them after emailing and saying this was good to release on CRAN and all the reverse dependencies that are affected are mine and I will fix them.

I tried to run your testing suite before I submitted and it seemed to be OK on my end.

**Comment by luyckxn** [comment]
I see. Thanks a lot for your help!
