### ISSUE TITLE
`zeroRe()` fails with correlated etas

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/rxode2#480]
I will fix this.

``` r
library(rxode2)
#> rxode2 2.0.12 using 8 threads (see ?getRxThreads)
#>   no cache: create with `rxCreateCache()`
library(nlmixr2lib)

mod <-
  readModelDb("PK_1cmt") %>%
  addEta(c("lcl", "lvc")) %>%
  ini(etalcl + etalvc ~ c(0.1, 0.05, 0.2))
#> ℹ parameter labels from comments are typically ignored in non-interactive mode
#> ℹ Need to run with the source intact to parse comments
#> ℹ parameter labels from comments are typically ignored in non-interactive mode
#> ℹ Need to run with the source intact to parse comments
#> ℹ promote `etalcl` to between subject variability with initial estimate 0.1
#> ℹ change initial estimate of `etalcl` to `0.1`
#> ℹ promote `etalvc` to between subject variability with initial estimate 0.1
#> ℹ change initial estimate of `etalvc` to `0.1`
#> ℹ parameter labels from comments are typically ignored in non-interactive mode
#> ℹ Need to run with the source intact to parse comments
#> ℹ change initial estimate of `etalcl` to `0.1`
#> ℹ add covariance between `etalvc` and `etalcl` with initial estimate `0.05`
#> ℹ change initial estimate of `etalvc` to `0.2`
zeroRe(mod)
#> Error: vectors and list need to named numeric expression
```

<sup>Created on 2023-03-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mattfidler** [comment]
I'm a bit confused by the question

- The model covariance matrix isn't stored in a `rxode2` ui object unless it comes from `nonmem2rx` currently.  
- The `omega` covariance matrix is stored in the `$iniDf`, and all the eta matrix is touched with `ini()` .  Perhaps I don't know what you mean by "touching"

**Comment by billdenney** [comment]
I'm asking the second question about the omega covariance matrix.  I want to be able to directly set a covariance to zero without modifying the other parts of the omega matrix.  I'd like to do something like the following (but I realize that this would likely be a bad interface for it):

```
ini(model, "eta1,eta2 ~ 0.5")
```

And set the correlation to a new value of 0.1 without touching the value of eta1 or eta2.

**Comment by mattfidler** [comment]
That would require `.` to be a drop in replacement for the value and could be confusing from `magrittr` piping.

**Comment by billdenney** [comment]
Yeah, that would get complicated quickly.  I'll take another path.
