### ISSUE TITLE
`rxode2()` allows correlation with zero diagonal values in etas

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/rxode2#481]
I would think that any off-diagonal value must be zero when the diagonal is zero in an eta matrix, but this works.  Should this be an error?

``` r
library(rxode2)
#> rxode2 2.0.12 using 8 threads (see ?getRxThreads)
#>   no cache: create with `rxCreateCache()`
badcorr <- function() {
  ini({
    lka <- 0.45
    lcl <- 1
    lvc <- 3.45
    propSd <- fix(0)
    etalcl + etalvc ~ c(0, 0.05, 0)
  })
  model({
    ka <- exp(lka)
    cl <- exp(lcl + etalcl)
    vc <- exp(lvc + etalvc)
    cp <- linCmt()
    cp ~ prop(propSd)
  })
}

rxode2(badcorr)
#>  ── rxode2-based solved PK 1-compartment model with first-order absorption ────── 
#>  ── Initalization: ──  
#> Fixed Effects ($theta): 
#>    lka    lcl    lvc propSd 
#>   0.45   1.00   3.45   0.00 
#> 
#> Omega ($omega): 
#>        etalcl etalvc
#> etalcl   0.00   0.05
#> etalvc   0.05   0.00
#>  ── μ-referencing ($muRefTable): ──  
#>   theta    eta level
#> 1   lcl etalcl    id
#> 2   lvc etalvc    id
#> 
#>  ── Model (Normalized Syntax): ── 
#> function() {
#>     ini({
#>         lka <- 0.45
#>         lcl <- 1
#>         lvc <- 3.45
#>         propSd <- fix(0, 0)
#>         etalcl + etalvc ~ c(0, 0.05, 0)
#>     })
#>     model({
#>         ka <- exp(lka)
#>         cl <- exp(lcl + etalcl)
#>         vc <- exp(lvc + etalvc)
#>         cp <- linCmt()
#>         cp ~ prop(propSd)
#>     })
#> }
```

<sup>Created on 2023-03-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by billdenney** [comment]
@mattfidler, As I was looking through this, I was unsure of where to place the fix for this.  On one hand, initial estimates in `rxode2` and `nlmixr2est` need to have zero off-diagonals when there are zero diagonal values.  So, it seems like it belongs in `rxode2`.  On the other hand, the actual parsing of initial estimates occurs in `lotri`.

I'm not putting the fix in `lotri` because an off-diagonal can be nonzero with a diagonal that is zero in a general lower triangular matrix, so the fix seems to fit best here.

**Comment by mattfidler** [comment]
That is fine with me.

**Comment by billdenney** [comment]
As I look through this even more, I have a new thought:

I think that most (but not all) `ini` modifications pass through `ini()`.  I think that what would be easiest is to make a single `assertValidIni()` function that does all checking on ini values, and that method would be called whenever ini values are changed.  It's not immediately obvious to me that it would be a simple change or that there is one place to put that checking code, but what do you think of that as a concept?

**Comment by mattfidler** [comment]
We already have some assetions on types of valid ini.  Perhaps we can name this one and apply it for simulations and estimations.

**Comment by billdenney** [comment]
Can `rxode2` work with block diagonal matrices where some correlations may be zero such as these two lower triangular examples?  Can nlmixr2 work with each of these, too (or, does it depend on the estimation method)?

I know that this one is okay when blocks do not share diagonal elements:

```
x
0 x
0 x x
0 0 0 x
0 0 0 x x
```

Some diagonals are shared between blocks (note how `Y` is part of the second and third blocks):

```
x
0 x
0 x Y
0 0 x x
0 0 x x x
```

Would the zero at 4,3 be an issue?

```
x
0 x
0 x x
0 x 0 x
0 0 x x x
```

What I'm thinking of are the following `ini` assertions:

* `assertRxOmegaDiagonal`: A diagonal-only omega (specifically testing for all zero off-diagonals; zeros on the diagonal would be allowed)
* `assertRxOmegaBlockSimple`: A "simple" block omega where diagonal elements are only in a single block
* `assertRxOmegaBlock`: Any block omega where no off-diagonals are zero within a block

All of these would raise an error with a matrix that has a zero on the diagonal and a nonzero value in the same row/column, like `Y` in the following example:

```
0
Y x
0 x x
0 0 0 x
0 0 0 x x
```

What do you think?  Are there any other assertions that would be useful?  Should any of these be omitted?

**Comment by mattfidler** [comment]
> Can `rxode2` work with block diagonal matrices where some correlations may be zero such as these two lower triangular examples? Can nlmixr2 work with each of these, too (or, does it depend on the estimation method)?
> 
> I know that this one is okay when blocks do not share diagonal elements:
> 
> ```
> x
> 0 x
> 0 x x
> 0 0 0 x
> 0 0 0 x x
> ```
>

Yes, it depends on the estimation method.  It *can* work with these items but the zeros are not fixed, unlike NONMEM.

 
> Some diagonals are shared between blocks (note how `Y` is part of the second and third blocks):
> 
> ```
> x
> 0 x
> 0 x Y
> 0 0 x x
> 0 0 x x x
> ```
> 
> Would the zero at 4,3 be an issue?

Considering the above, the the zero would not be an issue as long as the matrix is positive definite, invertable.

> 
> ```
> x
> 0 x
> 0 x x
> 0 x 0 x
> 0 0 x x x
> ```

This would also be possible with the same caveats.

> 
> What I'm thinking of are the following `ini` assertions:
> 
> * `assertRxOmegaDiagonal`: A diagonal-only omega (specifically testing for all zero off-diagonals; zeros on the diagonal would be allowed)

This could be OK.  Currently not required for anthing.

> * `assertRxOmegaBlockSimple`: A "simple" block omega where diagonal elements are only in a single block

This is OK and is what is required for `nlme`; currently if it is not diagonal only the whole matrix is specified anyway.  Therefore this assertion is not currently required for anything.

> * `assertRxOmegaBlock`: Any block omega where no off-diagonals are zero within a block

This could also be fine, but isn't really required for anything at the moment.

> 
> All of these would raise an error with a matrix that has a zero on the diagonal and a nonzero value in the same row/column, like `Y` in the following example:
> 
> ```
> 0
> Y x
> 0 x x
> 0 0 0 x
> 0 0 0 x x
> ```

Currently this is not required.  A zero diagonal would mean that she correlations that are listed would also give zero.  It seems as sane as having a zero diagonal mean nothing is estimated.  If the variance is zero, the covariance is zero (but could be something else if only the diagonal was non-zero).

> 
> What do you think? Are there any other assertions that would be useful? Should any of these be omitted?

I think this covers it, though I'm unsure if they should always be an error or simply a warning.

**Comment by billdenney** [comment]
> I think this covers it, though I'm unsure if they should always be an error or simply a warning.

When I use some of these, they give errors that are hard to track down during estimation.  My idea is that it would be better to give errors during model creation or modification that pinpoint the issue.
