### ISSUE TITLE
Unable to install rxode2/nlmixr2 on Windows 11 Pro 

### ISSUE THREAD

**Issue by Dstix** [nlmixr2/rxode2#486]
I am trying to install rxode2 on a Windows 11 Pro machine. I set up a new project in Rstudio and I used the command `install.packages("rxode2")`. When I do this I get:

> `library(rxode2)`
Registered S3 method overwritten by 'rxode2':
  method                 from       
  as.data.frame.rxEtTran rxode2parse
Error: package or namespace load failed for ‘rxode2’:
 .onLoad failed in loadNamespace() for 'rxode2', details:
  call: NULL
  error: rxode2 compiled with rxode2parse with a different solving structure
can try: install.packages('rxode2', type='source')

When I run `install.packages('rxode2', type='source')`` I get (copying the last several lines of output):

> gcc  -I"C:/PROGRA~1/R/R-42~1.3/include" -DNDEBUG  -I'C:/work/work_25Mar2023_v1/renv/library/R-4.2/x86_64-w64-mingw32/rxode2parse/include' -I'C:/work/work_25Mar2023_v1/renv/library/R-4.2/x86_64-w64-mingw32/rxode2random/include' -I'C:/work/work_25Mar2023_v1/renv/library/R-4.2/x86_64-w64-mingw32/rxode2et/include' -I'C:/work/work_25Mar2023_v1/renv/library/R-4.2/x86_64-w64-mingw32/PreciseSums/include' -I'C:/work/work_25Mar2023_v1/renv/library/R-4.2/x86_64-w64-mingw32/Rcpp/include' -I'C:/work/work_25Mar2023_v1/renv/library/R-4.2/x86_64-w64-mingw32/RcppArmadillo/include' -I'C:/work/work_25Mar2023_v1/renv/library/R-4.2/x86_64-w64-mingw32/BH/include'   -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"  -D_isrxode2_   -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c dscal.c -o dscal.o
gfortran  -fno-optimize-sibling-calls    -O2  -mfpmath=sse -msse2 -mstackrealign  -c dsphiv.f -o dsphiv.o
g++  -std=gnu++14 -I"C:/PROGRA~1/R/R-42~1.3/include" -DNDEBUG  -I'C:/work/work_25Mar2023_v1/renv/library/R-4.2/x86_64-w64-mingw32/rxode2parse/include' -I'C:/work/work_25Mar2023_v1/renv/library/R-4.2/x86_64-w64-mingw32/rxode2random/include' -I'C:/work/work_25Mar2023_v1/renv/library/R-4.2/x86_64-w64-mingw32/rxode2et/include' -I'C:/work/work_25Mar2023_v1/renv/library/R-4.2/x86_64-w64-mingw32/PreciseSums/include' -I'C:/work/work_25Mar2023_v1/renv/library/R-4.2/x86_64-w64-mingw32/Rcpp/include' -I'C:/work/work_25Mar2023_v1/renv/library/R-4.2/x86_64-w64-mingw32/RcppArmadillo/include' -I'C:/work/work_25Mar2023_v1/renv/library/R-4.2/x86_64-w64-mingw32/BH/include'   -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp -D_isrxode2_ -DBOOST_DISABLE_ASSERTS -DBOOST_NO_CXX11_STATIC_ASSERT -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -DBOOST_NO_AUTO_PTR -D_REENTRANT -I"C:/work/work_25Mar2023_v1/renv/library/R-4.2/x86_64-w64-mingw32/BH/include"   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c etTran.cpp -o etTran.o
etTran.cpp:333:10: fatal error: rxode2etConvertMethod.h: No such file or directory
  333 | #include <rxode2etConvertMethod.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** `[C:/PROGRA~1/R/R-42~1.3/etc/x64/Makeconf:260: etTran.o]` Error 1
ERROR: compilation failed for package 'rxode2'
* removing 'C:/work/work_25Mar2023_v1/renv/library/R-4.2/x86_64-w64-mingw32/rxode2'
* restoring previous 'C:/work/work_25Mar2023_v1/renv/library/R-4.2/x86_64-w64-mingw32/rxode2'

The downloaded source packages are in
	‘C:\Users\dstil\AppData\Local\Temp\Rtmpq8BXsm\downloaded_packages’
Warning message:
In utils::install.packages("rxode2", type = "source") :
  installation of package ‘rxode2’ had non-zero exit status

I have also tried using `pkgr install` from Metrum with no luck either. I am using RTools v4.2 and R-4.2.3. I suspect it is a file permission thing, but I am not sure.

**Comment by Dstix** [comment]
I was able to successfully install it with this command:

`install.packages(c("dparser", "rxode2ll", "rxode2parse",
                   "rxode2random", "rxode2et", "rxode2"),
                 repos=c(nlmixr2="https://nlmixr2.r-universe.dev",
                         CRAN="https://cloud.r-project.org"))`

Not sure what the difference is.

**Comment by billdenney** [comment]
We are currently in the middle of a CRAN submission, so the packages are in an inconsistent state until CRAN approves them all.  The easiest way to install right now is via R universe: https://github.com/nlmixr2/nlmixr2#install-using-the-r-universe

**Comment by billdenney** [comment]
@Dstix I'm glad that you found it before I wrote my comment.

**Comment by Dstix** [comment]
Thanks. 

Is this happening with nlmixr2 as well? I am running the example model:

> one.compartment <- function() {
  ini({
    tka <- 0.45 # Log Ka
    tcl <- 1 # Log Cl
    tv <- 3.45    # Log V
    eta.ka ~ 0.6
    eta.cl ~ 0.3
    eta.v ~ 0.1
    add.sd <- 0.7
  })
  
  >  model({
    ka <- exp(tka + eta.ka)
    cl <- exp(tcl + eta.cl)
    v <- exp(tv + eta.v)
    d/dt(depot) = -ka * depot
    d/dt(center) = ka * depot - cl / v * center
    cp = center / v
    cp ~ add(add.sd)
  })
}

`fit <- nlmixr2(one.compartment, theo_sd,  est="saem", saemControl(print=0))`

and I am getting the following error:

`ℹ parameter labels from comments will be replaced by 'label()'
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 1, 0
Error: arguments imply differing number of rows: 1, 0`

**Comment by billdenney** [comment]
I would guess that it applies to everything.  Doing a full R universe install for nlmixr2 and all dependencies should fix it, I think.

**Comment by Dstix** [comment]
OK - when do you think rxode2 and nlmixr2 will be ready for a typical pkgr install?

**Comment by mattfidler** [comment]
Whenever cran approves.  It has been 7 days so far.  We hope soon.

**Comment by mattfidler** [comment]
`nlmixr2est` was released on CRAN today, so within a few weeks (or maybe even now) you should be able to use `pkgr`
