### ISSUE TITLE
Simplify `zeroRe()`

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/rxode2#490]
> Just curious, why not simply modify `iniDf` directly?  It would likely be faster for the joint case since you don't have to compress/decompress more than once.

_Originally posted by @mattfidler in https://github.com/nlmixr2/rxode2/issues/482#issuecomment-1487900001_

**Comment by mattfidler** [comment]
Also if you modify `iniDf` you can then use:

```r
ini(oldUi)<- newIniDf
```

To "simplify" the assignment.

**Comment by billdenney** [comment]
That's way simpler. I didn't know that was an option, either.

**Comment by mattfidler** [comment]
It has entered with the new rxode2.  There is `rxode2(model) <-`, `ini(model) <-`, and `model(model) <-`
