### ISSUE TITLE
Allow skipping of doses?

### ISSUE THREAD

**Issue by mattfidler** [nlmixr2/rxode2#491]
Need for ss + lag, could make interface, like:

```r
skipDose(depot) = 3 # skip next 3 doses...
```

**Comment by mattfidler** [comment]
Would have to consider how to handle on/off infusion times -- is it one dose?

Perhaps that means it wouldn't be as useful...?

**Comment by billdenney** [comment]
I had always thought of any steady state to be a collection of measurements and doses that provide consistent results with repetition.  From the first to the last measure or dose of the interval, just keep doing that until the change is less than the tolerance.

So, I don't understand why this feature is required.

**Comment by mattfidler** [comment]
Infusions.   If you want more details we can discuss later.

**Comment by mattfidler** [comment]
Nope
