### ISSUE TITLE
Feature request: Export `.matchesLangTemplate()`

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/rxode2#515]
@mattfidler, would a simple PR to export `.matchesLangTemplate()` be okay to you?

I need it for some work I'm doing in `nlmixr2targets` to work with initial condition setting with `targets`.  Specifically, `targets` does not like `cmt(0) <- value` due to the `0`.  I've made an automatic translator that changes `cmt(initial) <- value` to `cmt(0) <- value` in a way that I think works with targets, and `.matchesLangTemplate()` can help find the right location(s).

**Comment by mattfidler** [comment]
That is fine with me, you wrote the function anyway.
