### ISSUE TITLE
Allow modeled bioavailability to run in parallel with `rxode2`

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/rxode2#517]
Wait, modeled rates, infusions, durations, lag-time and bioavailabilities cannot be run in parallel currently.  It corrupted the solve.

_Originally posted by @mattfidler in https://github.com/nlmixr2/nlmixr2est/issues/343#issuecomment-1532316222_

**Comment by mattfidler** [comment]
If it runs in `rxode2` it runs in `saem`

**Comment by mattfidler** [comment]
Fixed by #559
