### ISSUE TITLE
Cannot modify the `backTransform()` with `ini()`

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/rxode2#521]
I would have guessed that the below should work based on similarity to the `label()` argument.  (I realize that the parameter here is not actually on the log scale.)

``` r
library(rxode2)
#> rxode2 2.0.13.9000 using 8 threads (see ?getRxThreads)
#>   no cache: create with `rxCreateCache()`

mod1 <- function() {
  ini({
    # central 
    KA=2.94E-01
    CL=1.86E+01
    V2=4.02E+01
    # peripheral
    Q=1.05E+01
    V3=2.97E+02
    # effects
    Kin=1
    Kout=1
    EC50=200 
  })
  model({
    C2 <- centr/V2
    C3 <- peri/V3
    d/dt(depot) <- -KA*depot
    d/dt(centr) <- KA*depot - CL*C2 - Q*C2 + Q*C3
    d/dt(peri)  <- Q*C2 - Q*C3
    eff(0) <- 1
    d/dt(eff)   <- Kin - Kout*(1-C2/(EC50+C2))*eff
  })
}

ui <- rxode(mod1)
ui %>%
  ini(
    KA <- backTransform(exp())
  )
#> Error in backTransform(exp()): could not find function "backTransform"
```

<sup>Created on 2023-05-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mattfidler** [comment]
@billdenney 

We have a timeline now for release because of CRAN, if you want this included in the next release let me know.  For now I will not include it (implies that you will fix it before the next release in a couple of weeks)
