### ISSUE TITLE
Allow `ini(model) <- NULL` to drop the full ini block

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/rxode2#523]
Related to #520

When doing a PD fit contingent on a PK model, I will sometimes want to drop all parameters from the PK model to move them to the dataset.  What I currently do is:

`ini(ret) <- str2lang("ini({})")`

I think it would be simpler (and generally consistent with other R tools) to be able to do

`ini(ret) <- NULL`

**Comment by mattfidler** [comment]
This works only if there isn't a endpoint defined.
