### ISSUE TITLE
Model piping would be more useful if you could extract a line from the model too (to modify with regular expressions or parsing)

### ISSUE THREAD

**Issue by mattfidler** [nlmixr2/rxode2#533]
Maybe something like `modelExtract(lineLhs)`

**Comment by billdenney** [comment]
I have some API ideas for this (and I'm currently wrangling a 2 year old, so I can't elaborate).

**Comment by mattfidler** [comment]
To allow the Kiran to work on some of the things she wants to before I leave I will be working to integrate it today.  If there is some API things I missed, let me know.

**Comment by billdenney** [comment]
That covers the main bases.  The only other two things that I think would help are:

1. To give back the info on the line number within the model (maybe as an attribute?)
2. It's not immediately clear how the extraction would handle multiple assignment (e.g. `cl <- exp(lcl)` followed by `cl <- cl * exp(etacl)`).

**Comment by mattfidler** [comment]
> To give back the info on the line number within the model (maybe as an attribute?)

I suppose the line information could be useful.  Especially if you are modifying the model more as a whole.  However I think that may not be the common use case, so it is an argument to the function.

> It's not immediately clear how the extraction would handle multiple assignment (e.g. cl <- exp(lcl) followed by cl <- cl * exp(etacl)).

Both lines would be returned.  Model piping wouldn't work in this case, but if you modify the entire model, it could work...

One last thing I added is without specifying a variable it will extract most of the model and possibly the whole model statement (based on the `endpoint` argument)
