### ISSUE TITLE
ini: propose adding vector example to the documentation in help, and the piping website

### ISSUE THREAD

**Issue by iamstein** [nlmixr2/rxode2#536]
For ini, I'd propose adding an example of piping with a parameter vector (instead of just single parameter) to the help documentation and the website.  It's easy to do - just use a named vector as input!  But I only knew I could do this from talking to Matt.

**Comment by mattfidler** [comment]
Agreed, and add more new model piping items.

**Comment by mattfidler** [comment]
Moved to #563
