### ISSUE TITLE
Issue in installing rxode2ll

### ISSUE THREAD

**Issue by Sibojang9** [nlmixr2/rxode2#537]
It always stopped here prompting `"C:/Users/..../Documents/R/win-library/4.0/RcppParallel/lib/x64/tbb.dll: file not recognized: file format not recognized collect2.exe: error: ld returned 1 exit status no DLL was created ERROR: compilation failed for package 'rxode2ll"`

Then   `installation of package ‘rxode2ll’ had non-zero exit status`

Any solutions?  Thanks. 

Sibo

**Comment by billdenney** [comment]
@Sibojang9, I would guess that there is a mismatch between the versions of rxode2 and its dependencies that you're installing.  I also see that you're running R version 4.0.  There is a dependency issue with R 4.0 and the current versions of nlmixr2/rxode2:  https://nlmixr2.org/#r-package-installation

Please try those instructions, and a simpler path may be to install the current version of R, if possible.

**Comment by mattfidler** [comment]
Thanks Bill!

@Sibojang9 let us know if it works.

**Comment by Sibojang9** [comment]
Hi Mat and Bill,

It works for me. One of my colleagues had the same issue. I think adding a note/link of the R version issue to the homepage of RxODE can be quite beneficial for future new RxODE2 users. Thanks.
![snap1895](https://github.com/nlmixr2/rxode2/assets/11802171/65cd2512-7379-46b2-8ad1-5a0e1040b5b8)
