### ISSUE TITLE
Allow `rxode2` piping to specify if a parameter is a between subject variability, population parameter, or covariate (while piping in the `model` statement) 

### ISSUE THREAD

**Issue by iamstein** [nlmixr2/rxode2#543]
Below is a model and further below is the error I'm getting when trying to modify the model with piping.
```r
# model ----
  library(nlmixr2)
  model_pkpd_2stage <- function() {
    description <- "Two compartment PK model with linear clearance using differential equations"
    ini({
      lkout  <- log(6.5e-3); label("log(kout) for B cells")
      lr0    <- log(1.85); label("log(r0) Initial B cell level")
      lec50  <- log(118); label("log(EC50) for B cells")
      lemax  <- log(440); label("log(Emax) for B cells")
      omega2.r0 ~ .76^2; label("R0 variability")
      resp_add_sd <-  0.005 ; label("Additive residual error for B cells ")
      resp_prop_sd <- 0.3 ; label("Proportional residual error for B cells (fraction)")
    })
    model({
      k0   <- exp(lr0 + omega2.r0)
      kout <- exp(lkout)
      ec50 <- exp(lec50)
      emax <- exp(lemax)
      
      Cc   = 1
      
      resp(0) = r0;
      d/dt(resp)         = kin - kout*(1+emax*Cc/(ec50+Cc))*resp
      
      resp ~ add(resp_add_sd) + prop(resp_prop_sd)
    })
  }
```
 
This gives an error:
```
  model3 = model_pkpd_2stage %>%
    model(kout = exp(lkout + omega2.kout))
```
```
Error: syntax/parsing errors:
syntax error: 2+ single population parameters in a single mu-referenced expression: 'lkout', 'lr0'
this could occur when a between subject variability parameter is not initialized with a '~'
```

This works:
```
  model4 = model_pkpd_2stage %>%
    model(ec50 = exp(lec50 + omega2.ec50)) %>%
    model(emax = exp(lemax + omega2.emax))
```    
```
ℹ add covariate `omega2.ec50`
ℹ add covariate `omega2.emax`
```

I don't understand why the model3 code above gives an error while the model4 does not.  I also don't understand what the model3 error means.  Previously, I was also including `ini()` lines to specify the various omega2 parameters, but here I remove them, just to provide the simplest code that gives the error.

**Comment by mattfidler** [comment]
The implied type of parameter name I believe is useful.  

The whole divide between `omega` and `eta`s in `nlmixr2` can be a bit confusing...

**Comment by iamstein** [comment]
You said: "As a note, nlmixr2 doesn't require the naming conventions, only the piping does." but this is exactly what is confusing.  I imagine everyone will think of piping as a part of nlmixr and expect it all to work the same way.

If you really want it to work such that piping assumes things about the parameters based on their names to decide if they're a fixed or random effect, rather than being unambiguous or user specified, then I think you should at least output as a warning or message that assumptions about the parameters being a fixed or random effect are being made.

Personally, I'd rather the piping functions just be unambiguous in some way.

**Comment by mattfidler** [comment]
There will be another function `rxSetPipingAuto()` that will tell what type of variable the model is  It is in #559

**Comment by mattfidler** [comment]
Also in #559 is the ability to force the variable to be `cov`

```r
%>% model(cov="wt")
```

Given this is now true, I think you can control if something is a population parameter or covariate and you can change the `eta` like items to between subject variabilities by simply using `ini(eta~bsvVar)`.  

I will consider this closed for now since it will be addressed with the next release.
