### ISSUE TITLE
Feature request:  Allow variables that are lists/character vectors to be used in piping expressions

### ISSUE THREAD

**Issue by mattfidler** [nlmixr2/rxode2#552]
Like 

```r
> t <- c("-d/dt(peripheral1)", "-d/dt(peripheral2)")
> f %>% model(t)
```

**Comment by billdenney** [comment]
I also wanted to use character variable names in `rxRename()`.  My work-around was to run `str2lang()` on the character values first, but it would be simpler to accept either names or characters.
