### ISSUE TITLE
The function rxUnloadAll() is defined twice in utils.R

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/rxode2#6]
FYI, I found this while doing some documentation clean-ups, so please do not fix this until you've merged PR #5.

The first definition:

https://github.com/nlmixr2/rxode2/blob/d1bac25d849ccb0f7c43c9567d158901377a3ed4/R/utils.R#L52-L86

The second definition:

https://github.com/nlmixr2/rxode2/blob/d1bac25d849ccb0f7c43c9567d158901377a3ed4/R/utils.R#L995-L999

**Comment by mattfidler** [comment]
Fixed in e1bef345

**Comment by mattfidler** [comment]
Thanks for the catch @billdenney
