### ISSUE TITLE
Improve documentation for installation in Linux

### ISSUE THREAD

**Issue by Adam-Antios** [nlmixr2/rxode2#675]
I tried to install the package in Linux (Ubuntu 20.04) and I faced dozens of problems. I had installed all the necessary utilities listed in the documentation and I was always receiving errors for not having installed symengine. I even build it from source. The only thing that worked was installing the following:

https://github.com/symengine/symengine.R

I would like to ask you to improve the documentation with clear instructions as to which dependencies are needed and the steps required to install the rxode2.

**Comment by mattfidler** [comment]
Thanks. Done.

**Comment by Adam-Antios** [comment]
I mentioned my own experience. Was this actually a necessary step for Ubuntu or did I miss something else? I am trying to avoid misguiding someone.

**Comment by mattfidler** [comment]
It actually depends on how you setup R.  The package `r2u` handles all the dependencies needed for all packages.  So, you don't have to compile and you don't have to worry about dependencies (if you are on ubuntu). Other systems like redhat also have this, though I believe R is likely better tested on ubuntu variants.

**Comment by Adam-Antios** [comment]
Thank you very much for the clear explanation.
