### ISSUE TITLE
simulation with covariates and variability error message

### ISSUE THREAD

**Issue by amitvtaneja** [nlmixr2/rxode2#677]
hello

I get the following error with RxODE, when simulating with variability. the number of IDs in the simulation dataset is higher than the nSub. the error occurs even when i have an exact match of the two. As i understand, the number of ids input to iCOV, the event table and nSUB argument should correspond correct?

Secondly, i would like to simulate several dose cohorts, that receive different doses, at the same time. how can the event Table be modified such that i input one event table with different id numbers? If so, do the ids in the iCOV need to match those with the event table?

Currently i generate several event tables then rerun the model with different event tables and simulation seeds, but there must be a more efficient way.
Lastly, it seems the RXODE function does not take the case_when function as argument, when more than 2 conditions are needed to define a parameter, eg a categorical covariate with 3 or more levels.
Thanks

Amit Taneja

```r
Error in rxSolveSEXP(object, .ctl, .nms, .xtra, params, events, inits, :
provided multi-subject data (n=215) trying to simulate a different number of subjects (n=1000).
```

```r
rx1_c_ii <- RxODE({

CLMATF<-1-(1-beta_CL)exp(-(PAGE-(40/4.35))log(2)/T50_CL)
ALCL<-(WT / 70)^ AE_cl
#clcov<-ALCLCLMATF(1+ifelse(CLRACEN==1, beta1_CLRACEN,beta2_CLRACEN))(1+beta_CLADAADA)#(1+beta_CLSEASSEAS)
clcov<-ALCLCLMATF(1+(CLRACENbeta1_CLRACEN+(1-CLRACEN)beta2_CLRACEN))(1+beta_CLADAADA)(1+beta_CLSEASSEAS)
cl <- (tclclcov) exp(eta.cl)
ALV2<-(WT / 70)^ AE_v
v2cov<-ALV2*(1+beta_V2RACENCLRACEN)
v2 <- (tv2v2cov) * exp(eta.v2)
Q<-tq* (WT / 70)^ AE_cl
v3<- tv3 * (WT / 70)^ AE_v
ka <- tka * exp(eta.ka)
ipred <- linCmt()
obs <- ipred #* (1 + prop.sd) + add.sd
})


evw_d <- et( time.units="days") %>%
et(amt=50000) %>%
et(0, 150, length.out=1000) %>%
et(id=1:2000)

sim_e_ii <- rxSolve(rx1_c_ii, theta_b, evw_c, nSub=1000, nStud=10,
thetaMat=mat,
## Match boundaries of problem
thetaLower=0,
## Sigmas are standard deviations
sigmaXform="identity", # default sigma xform="identity"
omega=c("eta.cl", "eta.v2", "eta.ka"), ## etas are variances
omegaXform="variance", # default omega xform="variance"
iCov=covs_c,
dfSub=74, dfObs=476,c(fdepot=0.8498),keep=c("WT","PAGE","GA","ADA","CLRACEN"))

```

**Comment by mattfidler** [comment]
I seem to be missing the key components to reproduce this.

**Comment by mattfidler** [comment]
However, in general if you add the simulated covariates to the table `rx1_c_ii` you are likely go be able to simulate this.

If you need some more help, please provide a reproducible example so ti can help a bit further.

I'm unsure why this particular issue fell off of my radar.  Thank you for your patience.

**Comment by mattfidler** [comment]
It seems you want to have some more fine grain control of the covariates.  You can specify them as a data frame and solve them.

This is an example where that is done.  It is adapted from


https://nlmixr2.github.io/rxode2/articles/rxode2-pipeline.html?q=rxsim#simulating-from-a-data-frame-of-parameters

If you want to simulate with uncertainty in your population parameters you need the covariance matrix of the population parameters (which you did not provide):

``` r
library(rxode2)
#> rxode2 2.1.3 using 8 threads (see ?getRxThreads)
#>   no cache: create with `rxCreateCache()`
```

``` r
library(tidyverse)

#------------------------------------------------------------------------------------------------------------------------
PAGE_WT_Guk<-function(wmax,PAGE,gam,PMA50,alfa,beta_alfa){

  WT<- ((wmax*PAGE^gam)/ (PAGE^gam+PMA50^gam))*(1/exp(-alfa*PAGE)+beta_alfa)


  return(WT)

}


N<-5000

rbind(data.frame(PAGE=rlnorm(2500,log(10.8),log(2.2)),GA="29-<35wGA"),
      data.frame(PAGE=rlnorm(2500,log(11.9),log(2.28)),GA=">=35wGA"))->dat


dat %>% mutate(ID=1:N)->dat

covs_c<-dat %>% filter(PAGE>7 & PAGE<20) %>% slice_sample(n=1000) %>% mutate(WT=PAGE_WT_Guk(wmax=8.42,PAGE=PAGE*4,gam=4.53,PMA50=44.1,alfa=0.003299,beta_alfa=1/14.3),
                                                                             ADA=rbinom(1000,1,0.1),SEAS=rbinom(1000,1,0.1),
                                                                             CLRACEN=rbinom(1000,1,0.56))

covs_c <- covs_c %>%
  mutate(ID=seq_along(ADA))
#

rx1_c_ii <- function() {
  ini({
    tcl=39
    tv2=1980
    tka=0.401
    tv3=2400
    tq=709
    AE_cl=0.8
    AE_v=0.48
    beta_CLADA=0.124
    beta_CL=0.345
    beta1_CLRACEN=0.132
    beta2_CLRACEN=-0.0894
    T50_CL=14.8
    beta_CLSEAS=-0.122
    beta_V2RACEN=-0.122
    eta.cl + eta.v2 + eta.ka ~ c(0.0708898,
                                 0.0789256 , 0.162449  ,
                                 0, 0, 0.213755  )
  })
  model({
    CLMATF<-1-(1-beta_CL)*exp(-(PAGE-(40/4.35))*log(2)/T50_CL)
    ALCL<-(WT / 70)^ AE_cl
    #clcov<-ALCL*CLMATF*(1+ifelse(CLRACEN==1, beta1_CLRACEN,beta2_CLRACEN))*(1+beta_CLADA*ADA)#*(1+beta_CLSEAS*SEAS)
    clcov<-ALCL*CLMATF*(1+(CLRACEN*beta1_CLRACEN+(1-CLRACEN)*beta2_CLRACEN))*(1+beta_CLADA*ADA)*(1+beta_CLSEAS*SEAS)
    cl <- (tcl*clcov)* exp(eta.cl)
    ALV2<-(WT / 70)^ AE_v
    v2cov<-ALV2*(1+beta_V2RACEN*CLRACEN)
    v2 <- (tv2*v2cov) * exp(eta.v2)
    Q<-tq* (WT / 70)^ AE_cl
    v3<- tv3 * (WT / 70)^ AE_v
    ka <- tka * exp(eta.ka)
    ipred <- linCmt()
    obs <- ipred #* (1 + prop.sd) + add.sd
  })
}

rx1_c_ii <- rx1_c_ii()

r <- rx1_c_ii$simulationIniModel

pars <- rxInits(r)
pars <- pars[regexpr("(sd|eta)",names(pars)) == -1]
print(pars)
#>      tcl      tv2      tka      tv3       tq    AE_cl     AE_v   T50_CL 
#>   39.000 1980.000    0.401 2400.000  709.000    0.800    0.480   14.800
```

``` r

# You are simulating with uncertainly but have not input the covariance
# matrix correctly, you are using omega

d <- length(pars)

# Creating covariance matrix
tmp <- matrix(rnorm(d^2), d, d)
mcov <- tcrossprod(tmp, tmp)
dimnames(mcov) <- list(names(pars), names(pars))

# here is the "covariance" of the thetas
mcov
#>               tcl        tv2        tka        tv3         tq      AE_cl
#> tcl    11.8750216 -3.7769890 -2.5251766  2.5054911 -1.3068602  2.1953960
#> tv2    -3.7769890  5.9255777  0.4086845 -0.4713162 -1.8717303  1.7290220
#> tka    -2.5251766  0.4086845 10.5730048  1.0129404  2.2891452 -1.4309715
#> tv3     2.5054911 -0.4713162  1.0129404  5.4799456  0.4537806 -2.3210988
#> tq     -1.3068602 -1.8717303  2.2891452  0.4537806  5.8101845 -1.8142694
#> AE_cl   2.1953960  1.7290220 -1.4309715 -2.3210988 -1.8142694  4.9729933
#> AE_v   -2.4613129 -1.1192624  2.1933439 -2.7931341  1.2645622 -0.7185587
#> T50_CL  0.3981945 -2.2501997  2.8896261 -2.2533366 -0.7543249  0.7356002
#>              AE_v     T50_CL
#> tcl    -2.4613129  0.3981945
#> tv2    -1.1192624 -2.2501997
#> tka     2.1933439  2.8896261
#> tv3    -2.7931341 -2.2533366
#> tq      1.2645622 -0.7543249
#> AE_cl  -0.7185587  0.7356002
#> AE_v    4.1862933  0.3226331
#> T50_CL  0.3226331  8.1934534
```

``` r


df <- rxSimThetaOmega(params=pars, omega=rx1_c_ii$omega,
                      dfSub=74, dfObs=476,
                      thetaMat=mcov, thetaLower=0, nSub=100,nStud=10)

# you can see that the theta values change per study (the omega values do too)

# Now add the covariates you simulated
df <- df %>% mutate(ID=seq_along(tcl)) %>%
  merge(covs_c)

# Get the single event table
evw_d <- et( time.units="days") %>%
  et(amt=50000) %>%
  et(0, 150, length.out=200)


# and solve:
sim_e_ii  <- rxSolve(r, df %>% select(-GA), evw_d, keep=c("WT","PAGE","ADA","CLRACEN"))

plot(sim_e_ii, obs, log="y")
#> Warning in ggplot2::scale_y_log10(..., breaks = breaks, minor_breaks =
#> minor_breaks, : log-10 transformation introduced infinite values.
```

![](https://i.imgur.com/dO720Jh.png)

<sup>Created on 2024-05-24 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by amitvtaneja** [comment]
Thanks Matt, I took the example from here, but without the uncertainty, as i am interested only in simulating with variability. The matrix I create has only etas, so i guess in this case RXODE does use the variance correctly? Though i agree the correct way of specifying variability would have been by inputing an omega matrix to the argument omega.

Thanks

Amit

https://nlmixrdevelopment.github.io/RxODE/articles/RxODE-sim-var.html

**Comment by amitvtaneja** [comment]
hi Matt

thanks for the updated code. My intention was only to simulate with IIV. I guess in my code the Thetamat argument is not used, but the variance is used from the omegas, as required though the replicates are redundant.
In your code, the following does not run. simulationIniModel does not seem to be an output variable. Could you check this?


thanks


 r <- rx1_c_ii$simulationIniModel
 
 pars <- rxInits(r)
Error in rxInits(r) : 
  a NULL object does not have any rxode2 model variables

**Comment by mattfidler** [comment]
I'm sorry @amitvtaneja can you post a reproducible example so ti can help a bit more.

**Comment by amitvtaneja** [comment]
hello Matt,

I am simply re-running the example you posted above that gives me the error

#----------------error message
pars <- rxInits(r)
Error in rxInits(r) :
a NULL object does not have any rxode2 model variables



#--------------------------------code----------------------------------------------------------------------------------------
PAGE_WT_Guk<-function(wmax,PAGE,gam,PMA50,alfa,beta_alfa){

  WT<- ((wmax*PAGE^gam)/ (PAGE^gam+PMA50^gam))*(1/exp(-alfa*PAGE)+beta_alfa)


  return(WT)

}


N<-5000

rbind(data.frame(PAGE=rlnorm(2500,log(10.8),log(2.2)),GA="29-<35wGA"),
      data.frame(PAGE=rlnorm(2500,log(11.9),log(2.28)),GA=">=35wGA"))->dat


dat %>% mutate(ID=1:N)->dat

covs_c<-dat %>% filter(PAGE>7 & PAGE<20) %>% slice_sample(n=1000) %>% mutate(WT=PAGE_WT_Guk(wmax=8.42,PAGE=PAGE*4,gam=4.53,PMA50=44.1,alfa=0.003299,beta_alfa=1/14.3),
                                                                             ADA=rbinom(1000,1,0.1),SEAS=rbinom(1000,1,0.1),
                                                                             CLRACEN=rbinom(1000,1,0.56))

covs_c <- covs_c %>%
  mutate(ID=seq_along(ADA))
#

rx1_c_ii <- function() {
  ini({
    tcl=39
    tv2=1980
    tka=0.401
    tv3=2400
    tq=709
    AE_cl=0.8
    AE_v=0.48
    beta_CLADA=0.124
    beta_CL=0.345
    beta1_CLRACEN=0.132
    beta2_CLRACEN=-0.0894
    T50_CL=14.8
    beta_CLSEAS=-0.122
    beta_V2RACEN=-0.122
    eta.cl + eta.v2 + eta.ka ~ c(0.0708898,
                                 0.0789256 , 0.162449  ,
                                 0, 0, 0.213755  )
  })
  model({
    CLMATF<-1-(1-beta_CL)*exp(-(PAGE-(40/4.35))*log(2)/T50_CL)
    ALCL<-(WT / 70)^ AE_cl
    #clcov<-ALCL*CLMATF*(1+ifelse(CLRACEN==1, beta1_CLRACEN,beta2_CLRACEN))*(1+beta_CLADA*ADA)#*(1+beta_CLSEAS*SEAS)
    clcov<-ALCL*CLMATF*(1+(CLRACEN*beta1_CLRACEN+(1-CLRACEN)*beta2_CLRACEN))*(1+beta_CLADA*ADA)*(1+beta_CLSEAS*SEAS)
    cl <- (tcl*clcov)* exp(eta.cl)
    ALV2<-(WT / 70)^ AE_v
    v2cov<-ALV2*(1+beta_V2RACEN*CLRACEN)
    v2 <- (tv2*v2cov) * exp(eta.v2)
    Q<-tq* (WT / 70)^ AE_cl
    v3<- tv3 * (WT / 70)^ AE_v
    ka <- tka * exp(eta.ka)
    ipred <- linCmt()
    obs <- ipred #* (1 + prop.sd) + add.sd
  })
}

rx1_c_ii <- rx1_c_ii()

r <- rx1_c_ii$simulationIniModel

pars <- rxInits(r)

**Comment by mattfidler** [comment]
I dont currently have access to my computer.  However if it is the same code then you probably need to update nlmixr2.  

See nlmixr2CheckInstall to see whst needs to be done.

Matt

**Comment by amitvtaneja** [comment]
i have rxode2 , do i still require nlmixr2? I am only performing simulations

**Comment by mattfidler** [comment]
No, the function in `nlmixr2` checks to see if all the packages are up to date.  If you don't need/want it you can manually check.

**Comment by amitvtaneja** [comment]
Thanks Matt, this works,

Amit
