### ISSUE TITLE
Issue encountered with ev$expand()

### ISSUE THREAD

**Issue by kulaksp** [nlmixr2/rxode2#701]
Trying to manipulate the following ev after expansion. But expansion doesn't seem to be working. Any input?

>    ev = et()
>    ev = ev %>% et(id=1:10, amt=1:10, dosing.to=1, ii=14, addl=5, rate=(1:10)/(15/60/24), cmt=1) 
>    ev$expand()
'lst[j]':
 [1] "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""
Error: 'lst[j]' needs to be a integer vector
Called from: ev$expand()
Browse[1]> Q

Regards, Kulandayan "Karthik" Subramanian

**Comment by mattfidler** [comment]
Hi @kulaksp 

Added issue here:

https://github.com/nlmixr2/rxode2et/issues/43
