### ISSUE TITLE
issue en web page "Population simulation with rxode2"

### ISSUE THREAD

**Issue by nsk64** [nlmixr2/rxode2#709]
Hi

An example is given to "Simulate using variance/standard deviation standard errors"

However, it seems that the simulation used the "Covariance matrix of estimate" but not the "Standard Error" of Estimate.
Sorry if I am missing something.

best regards
Nicolas

**Comment by mattfidler** [comment]
Hi @nsk64 

I am assuming you mean

https://nlmixr2.github.io/rxode2/articles/rxode2-sim-var.html#simulate-using-variancestandard-deviation-standard-errors

Technically some of the methods of simulation (like the `"lkj"` and `"separation"`) simulate the covariance matrix and the standard deviations to create the eventual covariance matrix that is sampled with uncertainty.

As you said, this is not how you input parameters into the simulation so it can be misleading.

**Comment by nsk64** [comment]
Hi
Thanks for your reply.
I agree but as you are not using standard error (as said in the title), I am confused.
Thanks for your work.
Best regards
Nicolas



Le 17 juil. 2024 à 02:20, Matthew Fidler ***@***.***> a écrit :

﻿
Hi @nsk64 I am assuming you mean https: //nlmixr2. github. io/rxode2/articles/rxode2-sim-var. html#simulate-using-variancestandard-deviation-standard-errors Technically some of the methods of simulation (like the "lkj" and "separation") simulate


Hi @nsk64<https://urldefense.com/v3/__https://github.com/nsk64__;!!JQ5agg!cIIV6-NDSTXB20yPbDE92ubSiuWdDd3njTe6lC4w-JV2BS00VwIMQOA1Q67dL8vL70CrN1QC7T8gBObz67HgrMAEf0nrNA$>

I am assuming you mean

https://nlmixr2.github.io/rxode2/articles/rxode2-sim-var.html#simulate-using-variancestandard-deviation-standard-errors<https://urldefense.com/v3/__https://nlmixr2.github.io/rxode2/articles/rxode2-sim-var.html*simulate-using-variancestandard-deviation-standard-errors__;Iw!!JQ5agg!cIIV6-NDSTXB20yPbDE92ubSiuWdDd3njTe6lC4w-JV2BS00VwIMQOA1Q67dL8vL70CrN1QC7T8gBObz67HgrMA-EbYWDA$>

Technically some of the methods of simulation (like the "lkj" and "separation") simulate the covariance matrix and the standard deviations to create the eventual covariance matrix that is sampled with uncertainty.

As you said, this is not how you input parameters into the simulation so it can be misleading.
