### ISSUE TITLE
Remove transit compartment helpers

### ISSUE THREAD

**Issue by mattfidler** [nlmixr2/rxode2#92]
Can simply use an ODE.  There are situations where this particular feature does not work.  Reduces complexity if this is removed as well.

**Comment by billdenney** [comment]
We should put transit compartment models into the model library.

**Comment by mattfidler** [comment]
Sure,

An example is here:

https://github.com/nlmixrdevelopment/nlmixr/issues/594#issuecomment-1051569405

In theory it can also use `tad(depot)` but I was having some problems with the `CRAN` nlmixr with this approach.


For me the biggest reason for removal is because the helpers are too inflexible.  In the current case, multiple compartment transit adsorptions (ie depot1 and depot2) are not possible and it may invalidate the case where there is a bolus to the central compartment but not the depot.

Of course it also simplifies other things.

**Comment by mattfidler** [comment]
The `transitAbs` has been replaced with `evid=7` and `transit()` functions
